# Итерационные методы решения СЛАУ

In [1]:
import sys

sys.path.append('..')

### 1. Метод Гаусса-Зейделя

In [10]:
import numpy as np
from modules.slae.solver.iterative.gauss_seidel import gauss_seidel

a = np.array([
    [10., -4., 1.],
    [-4., 10., -4.],
    [1., -4., 10.]
])

b = np.array([-35., 41., 66.])

x, iter = gauss_seidel(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 19


array([-1.52136752,  7.37179487,  9.7008547 ])

##### Проверим найденное решение

Если $x$ решение $A * x = b$, то $r = A * x - b = 0$

In [11]:
r = np.dot(a, x) - b

r

array([-9.24160304e-10, -2.46430432e-10,  0.00000000e+00])

### 2. Метод Гаусса-Зейделя c релаксацией

In [12]:
from modules.slae.solver.iterative.gauss_seidel import gauss_seidel_relax

a = np.array([
    [10., -4., 1.],
    [-4., 10., -4.],
    [1., -4., 10.]
])

b = np.array([-35., 41., 66.])

x, iter = gauss_seidel_relax(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 16


array([-1.52136752,  7.37179487,  9.7008547 ])

In [13]:
r = np.dot(a, x) - b

r

array([ 1.52385127e-09,  4.13194812e-10, -1.06211928e-10])

### 3. Метод сопряженных градиентов

In [14]:
from modules.slae.solver.iterative.conjugate_gradient import conjugate_gradient

a = np.array([
    [10., -4., 1.],
    [-4., 10., -4.],
    [1., -4., 10.]
])

b = np.array([-35., 41., 66.])

x, iter = conjugate_gradient(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 3


array([-1.52136752,  7.37179487,  9.7008547 ])

In [15]:
r = np.dot(a, x) - b

r

array([ 7.10542736e-15, -7.10542736e-15,  0.00000000e+00])

### 4. Метод сопряженных градиентов для разреженной матрицы

In [16]:
from modules.slae.solver.iterative.conjugate_gradient import conjugate_gradient_sym_triplet

t = [
    [0, 0, 10.],
    [0, 1, -4.],
    [0, 2, 1.],
    [1, 1, 10.],
    [1, 2, -4.],
    [2, 2, 10.],
]

b = np.array([-35., 41., 66.])

x, iter = conjugate_gradient_sym_triplet(t, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 3


array([-1.43624525,  2.53865979,  3.87954422])

In [17]:
from modules.matrix.utils import matrix_sym_triplet_mult_vector

r = matrix_sym_triplet_mult_vector(t, x) - b

r

array([0.00000000e+00, 7.10542736e-15, 0.00000000e+00])