# Итерационные методы решения СЛАУ

In [6]:
import sys

sys.path.append('..')

### 1. Метод Гаусса-Зейделя

In [7]:
import numpy as np
from modules.slae.solver.iterative.gauss_seidel import gauss_seidel

a = np.array([
    [11., -5., 1.],
    [-5., 11., -5.],
    [1., -5., 11.]
])

b = np.array([10., 10., 10.])

x, iter = gauss_seidel(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 23


array([1.95121951, 2.68292683, 1.95121951])

##### Проверим найденное решение

Если $x$ решение $A * x = b$, то $r = A * x - b = 0$

In [15]:
r = np.dot(a, x) - b

r

array([-3., -1.,  3.])

### 2. Метод Гаусса-Зейделя c релаксацией

In [21]:
from modules.slae.solver.iterative.gauss_seidel import gauss_seidel_relax

a = np.array([
    [11., -5., 1.],
    [-5., 11., -5.],
    [1., -5., 11.]
])

b = np.array([10., 10., 10.])

x, iter = gauss_seidel_relax(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 18


array([1.95121951, 2.68292683, 1.95121951])

In [20]:
r = np.dot(a, x) - b

r

array([ 1.11010401e-09,  8.11333223e-11, -8.79563089e-11])

### 3. Метод сопряженных градиентов

In [22]:
from modules.slae.solver.iterative.conjugate_gradient import conjugate_gradient

a = np.array([
    [11., -5., 1.],
    [-5., 11., -5.],
    [1., -5., 11]
])

b = np.array([10., 10., 10.])

x, iter = conjugate_gradient(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 2


array([1.95121951, 2.68292683, 1.95121951])

In [23]:
r = np.dot(a, x) - b

r

array([-1.77635684e-15,  3.55271368e-15, -1.77635684e-15])

### 4. Метод сопряженных градиентов для разреженной матрицы

In [24]:
from modules.slae.solver.iterative.conjugate_gradient import conjugate_gradient_sym_triplet

t = [
    [0, 0, 11.],
    [0, 1, -5.],
    [0, 2, 1.],
    [1, 1, 11.],
    [1, 2, -5.],
    [2, 2, 11.],
]

b = np.array([10., 10., 10.])

x, iter = conjugate_gradient_sym_triplet(t, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 2


array([1.95121951, 2.68292683, 1.95121951])

In [25]:
from modules.matrix.utils import matrix_sym_triplet_mult_vector

r = matrix_sym_triplet_mult_vector(t, x) - b

r

array([-3.55271368e-15,  1.77635684e-15, -3.55271368e-15])