# Прямые методы решения СЛАУ

In [1]:
import sys

sys.path.append('..')

### 1. Метод Гаусса

In [2]:
import numpy as np
from modules.slae.solver.direct.gauss_elimination import gauss_elimination

a = np.array([
    [8., -4., 1.],
    [-4., 8., -4.],
    [1., -4., 8.]
])

b = np.array([4., 4., 4.])

x = gauss_elimination(np.copy(a), np.copy(b))

x

array([1.2, 1.7, 1.2])

##### Проверим найденное решение

Если $x$ решение $A * x = b$, то $r = A * x - b = 0$

In [3]:
r = np.dot(a, x) - b

r

array([0.0000000e+00, 8.8817842e-16, 0.0000000e+00])

### 2. LU разложение

In [5]:
from modules.slae.solver.direct.lu_decomposition import lu_decomposition, lu_solve

a = np.array([
    [8., -4., 1.],
    [-4., 8., -4.],
    [1., -4., 8.]
])

lu = lu_decomposition(a.copy())

b = np.array([4., 4., 4.])

x = lu_solve(lu, b.copy())

x

array([1.2, 1.7, 1.2])

In [6]:
r = np.dot(a, x) - b

r

array([0.0000000e+00, 8.8817842e-16, 0.0000000e+00])

### 3. Разложение Холецкого

In [7]:
from modules.slae.solver.direct.choleski_decomposition import choleski_decomposition, choleski_solve

a = np.array([
    [8., -4., 1.],
    [-4., 8., -4.],
    [1., -4., 8.]
])

chol = choleski_decomposition(a.copy())

b = np.array([4., 4., 4.])

x = choleski_solve(chol, b.copy())

x

array([1.2, 1.7, 1.2])

In [8]:
r = np.dot(a, x) - b

r

array([-1.77635684e-15,  4.44089210e-15, -1.77635684e-15])

### 4. Трехдиагональная матрица

In [9]:
from modules.slae.solver.direct.lu_decomposition import lu_3_diag_decomposition, lu_3_diag_solve

d = np.ones((5)) * 5.
c = np.ones((4)) * (-2)

b = np.array([4., 4., 4., 4., 4.])

e = c.copy()

ct, dt, et = lu_3_diag_decomposition(c.copy(), d.copy(), e.copy())
x = lu_3_diag_solve(ct, dt, et, b.copy())

x

array([1.90769231, 2.76923077, 3.01538462, 2.76923077, 1.90769231])

##### Проверим найденное решение

Если $x$ решение $A * x = b$, то $r = A * x - b = 0$

In [10]:
from modules.matrix.utils import matrix_3_diag_mult_vector

r = matrix_3_diag_mult_vector(c, d, e, x) - b

r

array([0., 0., 0., 0., 0.])