# Прямые методы решения СЛАУ

In [1]:
import sys

sys.path.append('..')

### 1. Метод Гаусса

##### Пример №1

In [2]:
import numpy as np
from modules.slae.solver.direct.gauss_elimination import gauss_elimination

a = np.array([
    [8., -3., 1.],
    [-3., 8., -3.],
    [1., -3., 8.]
])

b = np.array([-3., 4., 6.])

x = gauss_elimination(np.copy(a), np.copy(b))

x

array([-0.1984127 ,  0.83333333,  1.08730159])

##### Проверим найденное решение

Если $x$ решение $A * x = b$, то $r = A * x - b = 0$

In [3]:
r = np.dot(a, x) - b

r

array([ 0.0000000e+00, -8.8817842e-16, -8.8817842e-16])

In [4]:
r = np.dot(a, x) - b

r

array([ 0.0000000e+00, -8.8817842e-16, -8.8817842e-16])

### 2. LU разложение

##### Пример №1

In [5]:
from modules.slae.solver.direct.lu_decomposition import lu_decomposition, lu_solve

a = np.array([
    [8., -3., 1.],
    [-3., 8., -3.],
    [1., -3., 8.]
])

lu = lu_decomposition(a.copy())

b = np.array([-3., 4., 6.])

x = lu_solve(lu, b.copy())

x

array([-0.1984127 ,  0.83333333,  1.08730159])

In [6]:
r = np.dot(a, x) - b

r

array([ 0.0000000e+00, -8.8817842e-16, -8.8817842e-16])

### 3. Разложение Холецкого

##### Пример №1

In [8]:
from modules.slae.solver.direct.choleski_decomposition import choleski_decomposition, choleski_solve

a = np.array([
    [8., -3., 1.],
    [-3., 8., -3.],
    [1., -3., 8.]
])

chol = choleski_decomposition(a.copy())

b = np.array([-3., 4., 6.])

x = choleski_solve(chol, b.copy())

x

array([-0.1984127 ,  0.83333333,  1.08730159])

In [9]:
r = np.dot(a, x) - b

r

array([ 0.0000000e+00,  0.0000000e+00, -8.8817842e-16])

### 4. Трехдиагональная матрица

In [10]:
from modules.slae.solver.direct.lu_decomposition import lu_3_diag_decomposition, lu_3_diag_solve

d = np.ones((5)) * 5.
c = np.ones((4)) * (-1)

b = np.array([4., -11., 14., -15., 15.])

e = c.copy()

ct, dt, et = lu_3_diag_decomposition(c.copy(), d.copy(), e.copy())
x = lu_3_diag_solve(ct, dt, et, b.copy())

x

array([ 0.46022727, -1.69886364,  2.04545455, -2.07386364,  2.58522727])

##### Проверим найденное решение

Если $x$ решение $A * x = b$, то $r = A * x - b = 0$

In [11]:
from modules.matrix.utils import matrix_3_diag_mult_vector

r = matrix_3_diag_mult_vector(c, d, e, x) - b

r

array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       1.77635684e-15])