# Собственные значения и вектора матрицы

##### Нахождение собственного значения и вектора матрицы

In [1]:
import numpy as np

a = np.array([[8, -4, 1], [-4, 8, -4], [1, -4, 8]])

eigenvalues, eigenvectors = np.linalg.eig(a)

print("Собственные значения:")
print(eigenvalues)

print("\nСобственные векторы:")
print(eigenvectors)

Собственные значения:
[14.17890835  7.          2.82109165]

Собственные векторы:
[[-5.21546999e-01  7.07106781e-01  4.77481651e-01]
 [ 6.75261027e-01 -1.19956080e-16  7.37578840e-01]
 [-5.21546999e-01 -7.07106781e-01  4.77481651e-01]]


##### Нормы собственных векторов

In [2]:
m = len(eigenvalues)

for i in range(m):
    print(f'Норма собственного вектора для λ = {eigenvalues[i]}, есть {np.dot(eigenvectors[:, i], eigenvectors[:, i])}')

Норма собственного вектора для λ = 14.178908345800274, есть 0.9999999999999999
Норма собственного вектора для λ = 7.000000000000004, есть 0.9999999999999999
Норма собственного вектора для λ = 2.8210916541997273, есть 0.9999999999999998


##### Проверим найденные собственные значения

$$A \cdot x = \lambda \cdot x$$

$$(A - \lambda I) \cdot x = 0$$

In [3]:
n = len(eigenvectors[0])

for i in range(m):
    b = np.diag([eigenvalues[i]] * n)
    c = a - b

    print('---')
    print(f'Проверка собственного значения λ = {eigenvalues[i]}')
    print(f'Детерминант матрицы A - λI = {np.linalg.det(c)}')
    print(f'(A - λI)x = {np.dot(c, eigenvectors[:, i])}')

---
Проверка собственного значения λ = 14.178908345800274
Детерминант матрицы A - λI = 0.0
(A - λI)x = [-1.44328993e-15 -8.88178420e-16  1.47886977e-16]
---
Проверка собственного значения λ = 7.000000000000004
Детерминант матрицы A - λI = 1.332267629550184e-13
(A - λI)x = [-2.44249065e-15 -8.88178420e-16  3.80631873e-15]
---
Проверка собственного значения λ = 2.8210916541997273
Детерминант матрицы A - λI = -4.453939452773451e-14
(A - λI)x = [ 6.66133815e-16 -3.10862447e-15  2.24264718e-15]
