# Итерационные методы решения СЛАУ

In [31]:
import sys

sys.path.append('..')

### 1. Метод Гаусса-Зейделя

In [32]:
import numpy as np
from modules.slae.solver.iterative.gauss_seidel import gauss_seidel

a = np.array([
    [12., -3., 1.],
    [-3.,12., -3.],
    [1., -3., 12.]
])

b = np.array([100., 100., 100.])

x, iter = gauss_seidel(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 11


array([10.86956522, 13.76811594, 10.86956522])

##### Проверим найденное решение

Если $x$ решение $A * x = b$, то $r = A * x - b = 0$

In [33]:
r = np.dot(a, x) - b

r

array([ 7.31375849e-10, -4.68105554e-11,  0.00000000e+00])

### 2. Метод Гаусса-Зейделя c релаксацией

In [34]:
from modules.slae.solver.iterative.gauss_seidel import gauss_seidel_relax

a = np.array([
    [12., -3., 1.],
    [-3., 12., -3.],
    [1., -3., 12.]
])

b = np.array([100., 100., 100.])

x, iter = gauss_seidel_relax(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 11


array([10.86956522, 13.76811594, 10.86956522])

In [35]:
r = np.dot(a, x) - b

r

array([ 7.31375849e-10, -4.68105554e-11,  0.00000000e+00])

### 3. Метод сопряженных градиентов

In [36]:
from modules.slae.solver.iterative.conjugate_gradient import conjugate_gradient

a = np.array([
    [12., -3., 1.],
    [-3., 12., -3.],
    [1., -3., 12.]
])

b = np.array([100., 100., 100.])

x, iter = conjugate_gradient(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 2


array([10.86956522, 13.76811594, 10.86956522])

In [37]:
r = np.dot(a, x) - b

r

array([0., 0., 0.])

### 4. Метод сопряженных градиентов для разреженной матрицы

In [38]:
from modules.slae.solver.iterative.conjugate_gradient import conjugate_gradient_sym_triplet

t = [
    [0, 0, 12.],
    [0, 1, -3.],
    [0, 2, 1.],
    [1, 1, 12.],
    [1, 2, -3.],
    [2, 2, 12.]
]

b = np.array([100., 100., 100.])

x, iter = conjugate_gradient_sym_triplet(t, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 2


array([10.86956522, 13.76811594, 10.86956522])

In [39]:
from modules.matrix.utils import matrix_sym_triplet_mult_vector

r = matrix_sym_triplet_mult_vector(t, x) - b

r

array([0., 0., 0.])