# Прямые методы решения СЛАУ

In [1]:
import sys

sys.path.append('..')

### 1. Метод Гаусса

In [2]:
import numpy as np
from modules.slae.solver.direct.gauss_elimination import gauss_elimination

a = np.array([
    [11., -4., 1.],
    [-4., 11., -4.],
    [1., -4., 11.]
])

b = np.array([-2., 1., 6.])

x = gauss_elimination(np.copy(a), np.copy(b))

x

array([-0.14,  0.28,  0.66])

##### Проверим найденное решение

Если $x$ решение $A * x = b$, то $r = A * x - b = 0$

In [3]:
r = np.dot(a, x) - b

r

array([ 0.00000000e+00, -4.44089210e-16,  1.77635684e-15])

### 2. LU разложение

In [4]:
from modules.slae.solver.direct.lu_decomposition import lu_decomposition, lu_solve

a = np.array([
    [11., -4., 1.],
    [-4., 11., -4.],
    [1., -4., 11.]
])

lu = lu_decomposition(a.copy())

b = np.array([-2., 1., 6.])

x = lu_solve(lu, b.copy())

x

array([-0.14,  0.28,  0.66])

In [5]:
r = np.dot(a, x) - b

r

array([ 0.00000000e+00, -4.44089210e-16,  1.77635684e-15])

### 3. Разложение Холецкого

In [6]:
from modules.slae.solver.direct.choleski_decomposition import choleski_decomposition, choleski_solve

a = np.array([
    [11., -4., 1.],
    [-4., 11., -4.],
    [1., -4., 11.]
])

chol = choleski_decomposition(a.copy())

b = np.array([-2., 1., 6.])

x = choleski_solve(chol, b.copy())

x

array([-0.14,  0.28,  0.66])

In [7]:
r = np.dot(a, x) - b

r

array([ 0.0000000e+00,  0.0000000e+00, -8.8817842e-16])

### 4. Трехдиагональная матрица

In [8]:
from modules.slae.solver.direct.lu_decomposition import lu_3_diag_decomposition, lu_3_diag_solve

d = np.ones((5)) * 8.
c = np.ones((4)) * (-2)

b = np.array([3., -1., 4., -2., 2.])

e = c.copy()

ct, dt, et = lu_3_diag_decomposition(c.copy(), d.copy(), e.copy())
x = lu_3_diag_solve(ct, dt, et, b.copy())

x

array([ 0.40064103,  0.1025641 ,  0.50961538, -0.06410256,  0.23397436])

##### Проверим найденное решение

Если $x$ решение $A * x = b$, то $r = A * x - b = 0$

In [9]:
from modules.matrix.utils import matrix_3_diag_mult_vector

r = matrix_3_diag_mult_vector(c, d, e, x) - b

r

array([ 0.0000000e+00,  0.0000000e+00, -4.4408921e-16,  0.0000000e+00,
        0.0000000e+00])