# Итерационные методы решения СЛАУ

In [2]:
import sys

sys.path.append('..')

### 1. Метод Гаусса-Зейделя

In [4]:
import numpy as np
from modules.slae.solver.iterative.gauss_seidel import gauss_seidel

a = np.array([
    [8., -3., 1.],
    [-3., 8., -3.],
    [1., -3., 8.]
])

b = np.array([-3., 4., 6.])

x, iter = gauss_seidel(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 15


array([-0.1984127 ,  0.83333333,  1.08730159])

##### Проверим найденное решение

Если $x$ решение $A * x = b$, то $r = A * x - b = 0$

In [5]:
r = np.dot(a, x) - b

r

array([-5.16862553e-10, -7.06390502e-11,  0.00000000e+00])

### 2. Метод Гаусса-Зейделя c релаксацией

In [6]:
from modules.slae.solver.iterative.gauss_seidel import gauss_seidel_relax

a = np.array([
    [8., -3., 1.],
    [-3., 8., -3.],
    [1., -3., 8.]
])

b = np.array([-3., 4., 6.])

x, iter = gauss_seidel_relax(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 15


array([-0.1984127 ,  0.83333333,  1.08730159])

In [7]:
r = np.dot(a, x) - b

r

array([ 4.20286028e-11,  2.01705319e-11, -3.13349346e-12])

### 3. Метод сопряженных градиентов

In [8]:
from modules.slae.solver.iterative.conjugate_gradient import conjugate_gradient

a = np.array([
    [8., -3., 1.],
    [-3., 8., -3.],
    [1., -3., 8.]
])

b = np.array([-3., 4., 6.])

x, iter = conjugate_gradient(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 3


array([-0.1984127 ,  0.83333333,  1.08730159])

In [9]:
r = np.dot(a, x) - b

r

array([ 0.0000000e+00, -8.8817842e-16, -8.8817842e-16])

### 4. Метод сопряженных градиентов для разреженной матрицы

In [10]:
from modules.slae.solver.iterative.conjugate_gradient import conjugate_gradient_sym_triplet

t = [
    [0, 0, 8.],
    [0, 1, -3.],
    [0, 2, 1.],
    [1, 1, 8.],
    [1, 2, -3.],
    [2, 2, 8.]
]

b = np.array([-3., 4., 6.])

x, iter = conjugate_gradient_sym_triplet(t, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 3


array([-0.15826772,  0.30314961,  0.44173228])

In [11]:
from modules.matrix.utils import matrix_sym_triplet_mult_vector

r = matrix_sym_triplet_mult_vector(t, x) - b

r

array([ 4.4408921e-16, -4.4408921e-16,  0.0000000e+00])