# Итерационные методы решения СЛАУ

In [1]:
import sys

sys.path.append('..')

### 1. Метод Гаусса-Зейделя

In [5]:
import numpy as np
from modules.slae.solver.iterative.gauss_seidel import gauss_seidel

a = np.array([
    [12., -3., 1.],
    [-3.,12., -3.],
    [1., -3., 12.]
])

b = np.array([-11., 5., 21.])

x, iter = gauss_seidel(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 11


array([-0.91106719,  0.6884058 ,  1.99802372])

##### Проверим найденное решение

Если $x$ решение $A * x = b$, то $r = A * x - b = 0$

In [3]:
r = np.dot(a, x) - b

r 

array([ 1.38690837e-10, -5.69855274e-12,  0.00000000e+00])

### 2. Метод Гаусса-Зейделя c релаксацией

In [4]:
from modules.slae.solver.iterative.gauss_seidel import gauss_seidel_relax

a = np.array([
    [12., -3., 1.],
    [-3., 12., -3.],
    [1., -3., 12.]
])

b = np.array([-11., 5., 21.])

x, iter = gauss_seidel_relax(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 11


array([-0.91106719,  0.6884058 ,  1.99802372])

In [6]:
r = np.dot(a, x) - b

r

array([ 1.38690837e-10, -5.69855274e-12,  0.00000000e+00])

### 3. Метод сопряженных градиентов

In [7]:
from modules.slae.solver.iterative.conjugate_gradient import conjugate_gradient

a = np.array([
    [12., -3., 1.],
    [-3., 12., -3.],
    [1., -3., 12.]
])

b = np.array([-11., 5., 21.])

x, iter = conjugate_gradient(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 3


array([-0.91106719,  0.6884058 ,  1.99802372])

In [8]:
r = np.dot(a, x) - b

r

array([ 0.0000000e+00, -8.8817842e-16,  0.0000000e+00])

### 4. Метод сопряженных градиентов для разреженной матрицы

In [9]:
from modules.slae.solver.iterative.conjugate_gradient import conjugate_gradient_sym_triplet

t = [
    [0, 0, 12.],
    [0, 1, -3.],
    [0, 2, 1.],
    [1, 1, 12.],
    [1, 2, -3.],
    [2, 2, 12.],
]

b = np.array([-11., 5., 21.])

x, iter = conjugate_gradient_sym_triplet(t, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 3


array([-0.91106719,  0.6884058 ,  1.99802372])

In [10]:
from modules.matrix.utils import matrix_sym_triplet_mult_vector

r = matrix_sym_triplet_mult_vector(t, x) - b

r

array([ 0.0000000e+00, -8.8817842e-16,  0.0000000e+00])