# Задание №2

In [1]:
import sys

sys.path.append('..')

### 1. Метод Гаусса

In [2]:
import numpy as np
from modules.slae.solver.direct.gauss_elimination import gauss_elimination

a = np.array([
    [12., -4., 1.],
    [-4., 12., -4.],
    [1., -4., 12.]
])

b = np.array([-1., 51., 212.])

x = gauss_elimination(np.copy(a), np.copy(b))

x

array([ 2.17302053, 12.15322581, 21.53665689])

##### Проверим найденное решение

Если $x$ решение $A * x = b$, то $r = A * x - b = 0$

In [3]:
r = np.dot(a, x) - b

r

array([ 0.00000000e+00, -1.42108547e-14,  0.00000000e+00])

### 2. LU разложение

In [4]:
from modules.slae.solver.direct.lu_decomposition import lu_decomposition, lu_solve

a = np.array([
    [12., -4., 1.],
    [-4., 12., -4.],
    [1., -4., 12.]
])

lu = lu_decomposition(a.copy())

b = np.array([-1., 51., 212.])

x = lu_solve(lu, b.copy())

x

array([ 2.17302053, 12.15322581, 21.53665689])

In [5]:
r = np.dot(a, x) - b

r

array([ 0.00000000e+00, -1.42108547e-14,  0.00000000e+00])

### 3. Разложение Холецкого

In [6]:
from modules.slae.solver.direct.choleski_decomposition import choleski_decomposition, choleski_solve

a = np.array([
    [12., -4., 1.],
    [-4., 12., -4.],
    [1., -4., 12.]
])

chol = choleski_decomposition(a.copy())

b = np.array([-1., 51., 212.])

x = choleski_solve(chol, b.copy())

x

array([ 2.17302053, 12.15322581, 21.53665689])

In [7]:
r = np.dot(a, x) - b

r

array([ 0.00000000e+00, -1.42108547e-14,  0.00000000e+00])

### 4. Трехдиагональная матрица

In [8]:
from modules.slae.solver.direct.lu_decomposition import lu_3_diag_decomposition, lu_3_diag_solve

d = np.ones((5)) * 9.
c = np.ones((4)) * (-4)

b = np.array([11., 22., 33., 44., 55.])

e = c.copy()

ct, dt, et = lu_3_diag_decomposition(c.copy(), d.copy(), e.copy())
x = lu_3_diag_solve(ct, dt, et, b.copy())

x

array([ 7.4991453 , 14.12307692, 18.77777778, 19.87692308, 14.94529915])

##### Проверим найденное решение

Если $x$ решение $A * x = b$, то $r = A * x - b = 0$

In [9]:
from modules.matrix.utils import matrix_3_diag_mult_vector

r = matrix_3_diag_mult_vector(c, d, e, x) - b

r

array([0., 0., 0., 0., 0.])