# Прямые методы решения СЛАУ

In [3]:
import sys

sys.path.append('..')

### 1. Метод Гаусса

##### Пример №1

In [4]:
import numpy as np
from modules.slae.solver.direct.gauss_elimination import gauss_elimination

a = np.array([
    [6., -3., 1.],
    [-3., 6., -3.],
    [1., -3., 6.]
])

b = np.array([-14., 36., 6.])

x = gauss_elimination(np.copy(a), np.copy(b))

x

array([1.5, 9.5, 5.5])

##### Проверим найденное решение

Если $x$ решение $A * x = b$, то $r = A * x - b = 0$

In [ ]:
r = np.dot(a, x) - b

r

array([-1.77635684e-15,  2.13162821e-14, -3.55271368e-15])

### 2. LU разложение

In [7]:
from modules.slae.solver.direct.lu_decomposition import lu_decomposition, lu_solve

a = np.array([
    [6., -4., 1.],
    [-4., 6., -4.],
    [1., -4., 6.]
])

lu = lu_decomposition(a.copy())

b = np.array([-14., 36., 6.])

x = lu_solve(lu, b.copy())

x

array([10., 22., 14.])

In [8]:
r = np.dot(a, x) - b

r

array([-1.77635684e-15,  2.13162821e-14, -3.55271368e-15])

### 3. Разложение Холецкого

In [12]:
from modules.slae.solver.direct.choleski_decomposition import choleski_decomposition, choleski_solve

a = np.array([
    [6., -4., 1.],
    [-4., 6., -4.],
    [1., -4., 6.]
])

chol = choleski_decomposition(a.copy())

b = np.array([-14., 36., 6.])

x = choleski_solve(chol, b.copy())

x

array([10., 22., 14.])

In [13]:
r = np.dot(a, x) - b

r

array([ 1.77635684e-15, -2.13162821e-14,  3.55271368e-15])

### 4. Трехдиагональная матрица

In [5]:
from modules.slae.solver.direct.lu_decomposition import lu_3_diag_decomposition, lu_3_diag_solve

d = np.ones((5)) * 3.
c = np.ones((4)) * (-1)

b = np.array([11., -11., 14., -15., 15.])

e = c.copy()

ct, dt, et = lu_3_diag_decomposition(c.copy(), d.copy(), e.copy())
x = lu_3_diag_solve(ct, dt, et, b.copy())

x

array([ 3.16666667, -1.5       ,  3.33333333, -2.5       ,  4.16666667])

##### Проверим найденное решение

Если $x$ решение $A * x = b$, то $r = A * x - b = 0$

In [6]:
from modules.matrix.utils import matrix_3_diag_mult_vector

r = matrix_3_diag_mult_vector(c, d, e, x) - b

r

array([ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, -1.77635684e-15,
       -1.77635684e-15])