# Итерационные методы решения СЛАУ

In [ ]:
import sys

sys.path.append('..')

### 1. Метод Гаусса-Зейделя

In [ ]:
import numpy as np
from modules.slae.solver.iterative.gauss_seidel import gauss_seidel

a = np.array([
    [6., -3., 1.],
    [-3., 6., -3.],
    [1., -3., 6.]
])

b = np.array([-14., 36., 6.])

x, iter = gauss_seidel(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 14


array([3., 1., 1.])

##### Проверим найденное решение

Если $x$ решение $A * x = b$, то $r = A * x - b = 0$

In [3]:
r = np.dot(a, x) - b

r

array([-1.01250563e-10,  2.07674766e-10,  0.00000000e+00])

### 2. Метод Гаусса-Зейделя c релаксацией

In [4]:
from modules.slae.solver.iterative.gauss_seidel import gauss_seidel_relax

a = np.array([
    [6., -3., 1.],
    [-3., 6., -3.],
    [1., -3., 6.]
])

b = np.array([-14., 36., 6.])

x, iter = gauss_seidel_relax(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 14


array([3., 1., 1.])

In [5]:
r = np.dot(a, x) - b

r

array([ 9.97992800e-11,  2.38632225e-10, -2.16822116e-11])

### 3. Метод сопряженных градиентов

In [ ]:
from modules.slae.solver.iterative.conjugate_gradient import conjugate_gradient

a = np.array([
    [6., -3., 1.],
    [-3., 6., -3.],
    [1., -3., 6.]
])

b = np.array([-14., 36., 6.])

x, iter = conjugate_gradient(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 3


array([3., 1., 1.])

In [7]:
r = np.dot(a, x) - b

r

array([ 1.77635684e-15, -8.88178420e-16,  1.77635684e-15])

### 4. Метод сопряженных градиентов для разреженной матрицы

In [8]:
from modules.slae.solver.iterative.conjugate_gradient import conjugate_gradient_sym_triplet

t = [
    [0, 0, 6.],
    [0, 1, -3.],
    [0, 2, 1.],
    [1, 1, 6.],
    [1, 2, -3.],
    [2, 2, 6.]
]

b = np.array([-14., 36., 6.])

x, iter = conjugate_gradient_sym_triplet(t, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 3


array([ 0.54464286,  1.06696429, -0.73214286])

In [9]:
from modules.matrix.utils import matrix_sym_triplet_mult_vector

r = matrix_sym_triplet_mult_vector(t, x) - b

r

array([-8.88178420e-16, -1.77635684e-15,  3.55271368e-15])