# Собственные значения и вектора матрицы

### Пример №1

##### Нахождение собственного значения и вектора матрицы

In [3]:
import numpy as np

a = np.array([[11, -4, 1], [-4, 11, -4], [1, -4, 11]])

eigenvalues, eigenvectors = np.linalg.eig(a)

print("Собственные значения:")
print(eigenvalues)

print("\nСобственные векторы:")
print(eigenvectors)

Собственные значения:
[17.17890835 10.          5.82109165]

Собственные векторы:
[[-5.21546999e-01  7.07106781e-01  4.77481651e-01]
 [ 6.75261027e-01 -5.66666644e-16  7.37578840e-01]
 [-5.21546999e-01 -7.07106781e-01  4.77481651e-01]]


##### Нормы собственных векторов

In [4]:
m = len(eigenvalues)

for i in range(m):
    print(f'Норма собственного вектора для λ = {eigenvalues[i]}, есть {np.dot(eigenvectors[:, i], eigenvectors[:, i])}')

Норма собственного вектора для λ = 17.17890834580026, есть 0.9999999999999999
Норма собственного вектора для λ = 9.999999999999996, есть 1.0
Норма собственного вектора для λ = 5.821091654199727, есть 0.9999999999999998


##### Проверим найденные собственные значения

$$A \cdot x = \lambda \cdot x$$

$$(A - \lambda I) \cdot x = 0$$

In [5]:
n = len(eigenvectors[0])

for i in range(m):
    b = np.diag([eigenvalues[i]] * n)
    c = a - b

    print('---')
    print(f'Проверка собственного значения λ = {eigenvalues[i]}')
    print(f'Детерминант матрицы A - λI = {np.linalg.det(c)}')
    print(f'(A - λI)x = {np.dot(c, eigenvectors[:, i])}')

---
Проверка собственного значения λ = 17.17890834580026
Детерминант матрицы A - λI = 1.1604595674935735e-12
(A - λI)x = [-8.88178420e-15  8.88178420e-15 -7.26374166e-15]
---
Проверка собственного значения λ = 9.999999999999996
Детерминант матрицы A - λI = -1.0658141036401483e-13
(A - λI)x = [ 4.66293670e-15  0.00000000e+00 -4.02724187e-16]
---
Проверка собственного значения λ = 5.821091654199727
Детерминант матрицы A - λI = -4.453939452773451e-14
(A - λI)x = [ 2.27595720e-15 -1.99840144e-15 -6.32224464e-16]
