# Задание №2

In [1]:
import sys

sys.path.append('..')

### 1. Метод Гаусса

In [2]:
import numpy as np
from modules.slae.solver.direct.gauss_elimination import gauss_elimination

a = np.array([
    [131., -4., 1.],
    [-4., 131., -4.],
    [1., -4., 131.]
])

b = np.array([-1111., 6666., -1111.])

x = gauss_elimination(np.copy(a), np.copy(b))

x

array([-6.88742758, 50.46488992, -6.88742758])

##### Проверим найденное решение

Если $x$ решение $A * x = b$, то $r = A * x - b = 0$

In [3]:
r = np.dot(a, x) - b

r

array([ 0.00000000e+00,  0.00000000e+00, -2.27373675e-13])

### 2. LU разложение

In [4]:
from modules.slae.solver.direct.lu_decomposition import lu_decomposition, lu_solve

a = np.array([
    [131., -4., 1.],
    [-4., 131., -4.],
    [1., -4., 131.]
])

lu = lu_decomposition(a.copy())

b = np.array([-1111., 6666., -1111.])

x = lu_solve(lu, b.copy())

x

array([-6.88742758, 50.46488992, -6.88742758])

In [5]:
r = np.dot(a, x) - b

r

array([ 0.00000000e+00,  0.00000000e+00, -2.27373675e-13])

### 3. Разложение Холецкого

In [6]:
from modules.slae.solver.direct.choleski_decomposition import choleski_decomposition, choleski_solve

a = np.array([
    [131., -4., 1.],
    [-4., 131., -4.],
    [1., -4., 131.]
])

chol = choleski_decomposition(a.copy())

b = np.array([-1111., 6666., -1111.])

x = choleski_solve(chol, b.copy())

x

array([-6.88742758, 50.46488992, -6.88742758])

In [7]:
r = np.dot(a, x) - b

r

array([ 0.0000000e+00, -1.8189894e-12,  0.0000000e+00])

### 4. Трехдиагональная матрица

In [8]:
from modules.slae.solver.direct.lu_decomposition import lu_3_diag_decomposition, lu_3_diag_solve

d = np.ones((5)) * 191.
c = np.ones((4)) * (-4)

b = np.array([1111., 6662., 3333., 6664., 5555.])

e = c.copy()

ct, dt, et = lu_3_diag_decomposition(c.copy(), d.copy(), e.copy())
x = lu_3_diag_solve(ct, dt, et, b.copy())

x

array([ 6.55840131, 35.41366254, 18.94398496, 35.91161948, 29.83584543])

##### Проверим найденное решение

Если $x$ решение $A * x = b$, то $r = A * x - b = 0$

In [9]:
from modules.matrix.utils import matrix_3_diag_mult_vector

r = matrix_3_diag_mult_vector(c, d, e, x) - b

r

array([ 0.00000000e+00,  0.00000000e+00, -4.54747351e-13,  0.00000000e+00,
        0.00000000e+00])