# Собственные значения и вектора матрицы

##### Нахождение собственного значения и вектора матрицы

In [2]:
import numpy as np

a = np.array([[12, -3, 1], [-3, 12, -3], [1, -3, 12]])

eigenvalues, eigenvectors = np.linalg.eig(a)

print("Собственные значения:")
print(eigenvalues)

print("\nСобственные векторы:")
print(eigenvectors)

Собственные значения:
[16.77200187 11.          8.22799813]

Собственные векторы:
[[-5.28450837e-01  7.07106781e-01  4.69829451e-01]
 [ 6.64439182e-01 -4.42920901e-16  7.47342340e-01]
 [-5.28450837e-01 -7.07106781e-01  4.69829451e-01]]


##### Нормы собственных векторов

In [3]:
m = len(eigenvalues)

for i in range(m):
    print(f'Норма собственного вектора для λ = {eigenvalues[i]}, есть {np.dot(eigenvectors[:, i], eigenvectors[:, i])}')

Норма собственного вектора для λ = 16.772001872658777, есть 1.0
Норма собственного вектора для λ = 11.0, есть 1.0
Норма собственного вектора для λ = 8.227998127341234, есть 0.9999999999999999


##### Проверим найденные собственные значения

$$A \cdot x = \lambda \cdot x$$

$$(A - \lambda I) \cdot x = 0$$

In [4]:
m = len(eigenvalues)
n = len(eigenvectors[0])

for i in range(m):
    b = np.diag([eigenvalues[i]] * n)
    c = a - b

    print('---')
    print(f'Проверка собственного значения λ = {eigenvalues[i]}')
    print(f'Детерминант матрицы A - λI = {np.linalg.det(c)}')
    print(f'(A - λI)x = {np.dot(c, eigenvectors[:, i])}')

---
Проверка собственного значения λ = 16.772001872658777
Детерминант матрицы A - λI = -5.459794389378922e-13
(A - λI)x = [ 3.99680289e-15 -1.02140518e-14  4.50325485e-15]
---
Проверка собственного значения λ = 11.0
Детерминант матрицы A - λI = 0.0
(A - λI)x = [1.11022302e-16 3.33066907e-15 1.11022302e-16]
---
Проверка собственного значения λ = 8.227998127341234
Детерминант матрицы A - λI = 1.47721934559831e-14
(A - λI)x = [ 3.33066907e-15 -8.88178420e-16 -7.46003002e-16]
