# Собственные значения и вектора матрицы

##### Нахождение собственного значения и вектора матрицы

In [5]:
import numpy as np

a = np.array([[10, -4, 1], [-4, 10, -4], [1, -4, 10]])

eigenvalues, eigenvectors = np.linalg.eig(a)

print("Собственные значения:")
print(eigenvalues)

print("\nСобственные векторы:")
print(eigenvectors)

Собственные значения:
[16.17890835  9.          4.82109165]

Собственные векторы:
[[-5.21546999e-01  7.07106781e-01  4.77481651e-01]
 [ 6.75261027e-01 -1.31722752e-16  7.37578840e-01]
 [-5.21546999e-01 -7.07106781e-01  4.77481651e-01]]


##### Нормы собственных векторов

In [3]:
m = len(eigenvalues)

for i in range(m):
    print(f'Норма собственного вектора для λ = {eigenvalues[i]}, есть {np.dot(eigenvectors[:, i], eigenvectors[:, i])}')

Норма собственного вектора для λ = 16.178908345800266, есть 0.9999999999999998
Норма собственного вектора для λ = 9.000000000000002, есть 1.0
Норма собственного вектора для λ = 4.821091654199726, есть 1.0000000000000002


##### Проверим найденные собственные значения

$$A \cdot x = \lambda \cdot x$$

$$(A - \lambda I) \cdot x = 0$$

In [6]:
n = len(eigenvectors[0])

for i in range(m):
    b = np.diag([eigenvalues[i]] * n)
    c = a - b

    print('---')
    print(f'Проверка собственного значения λ = {eigenvalues[i]}')
    print(f'Детерминант матрицы A - λI = {np.linalg.det(c)}')
    print(f'(A - λI)x = {np.dot(c, eigenvectors[:, i])}')

---
Проверка собственного значения λ = 16.178908345800266
Детерминант матрицы A - λI = 5.866059352165318e-13
(A - λI)x = [-7.66053887e-15  2.22044605e-15 -3.55792734e-15]
---
Проверка собственного значения λ = 9.000000000000002
Детерминант матрицы A - λI = 5.329070518200769e-14
(A - λI)x = [-1.11022302e-15  1.33226763e-15  1.47811857e-15]
---
Проверка собственного значения λ = 4.821091654199726
Детерминант матрицы A - λI = 0.0
(A - λI)x = [-8.32667268e-16  6.66133815e-16  2.79177456e-17]
