# Собственные значения и вектора матрицы

##### Нахождение собственного значения и вектора матрицы

In [1]:
import numpy as np

a = np.array([[6, -3, 1], [-3, 6, -3], [1, -3, 6]])

eigenvalues, eigenvectors = np.linalg.eig(a)

print("Собственные значения:")
print(eigenvalues)

print("\nСобственные векторы:")
print(eigenvectors)

Собственные значения:
[10.77200187  5.          2.22799813]

Собственные векторы:
[[-5.28450837e-01  7.07106781e-01  4.69829451e-01]
 [ 6.64439182e-01 -5.20589282e-17  7.47342340e-01]
 [-5.28450837e-01 -7.07106781e-01  4.69829451e-01]]


##### Нормы собственных векторов

In [2]:
m = len(eigenvalues)

for i in range(m):
    print(f'Норма собственного вектора для λ = {eigenvalues[i]}, есть {np.dot(eigenvectors[:, i], eigenvectors[:, i])}')

Норма собственного вектора для λ = 10.772001872658763, есть 1.0
Норма собственного вектора для λ = 5.000000000000001, есть 1.0
Норма собственного вектора для λ = 2.227998127341235, есть 0.9999999999999999


##### Проверим найденные собственные значения

$$A \cdot x = \lambda \cdot x$$

$$(A - \lambda I) \cdot x = 0$$

In [3]:
n = len(eigenvectors[0])

for i in range(m):
    b = np.diag([eigenvalues[i]] * n)
    c = a - b

    print('---')
    print(f'Проверка собственного значения λ = {eigenvalues[i]}')
    print(f'Детерминант матрицы A - λI = {np.linalg.det(c)}')
    print(f'(A - λI)x = {np.dot(c, eigenvectors[:, i])}')

---
Проверка собственного значения λ = 10.772001872658763
Детерминант матрицы A - λI = 1.691767275582197e-13
(A - λI)x = [-1.66533454e-15  2.10942375e-15 -1.58850616e-15]
---
Проверка собственного значения λ = 5.000000000000001
Детерминант матрицы A - λI = 1.4210854715201997e-14
(A - λI)x = [ 5.55111512e-16 -3.10862447e-15  1.73826001e-15]
---
Проверка собственного значения λ = 2.227998127341235
Детерминант матрицы A - λI = -7.386096727991561e-15
(A - λI)x = [ 4.99600361e-16 -1.05471187e-15  6.70572362e-16]
