# Собственные значения и вектора матрицы

##### Нахождение собственного значения и вектора матрицы

In [1]:
import numpy as np

a = np.array([[131, -4, 1], [-4, 131, -4], [1, -4, 131]])

eigenvalues, eigenvectors = np.linalg.eig(a)

print("Собственные значения:")
print(eigenvalues)

print("\nСобственные векторы:")
print(eigenvectors)

Собственные значения:
[137.17890835 130.         125.82109165]

Собственные векторы:
[[-5.21546999e-01  7.07106781e-01  4.77481651e-01]
 [ 6.75261027e-01 -6.26799465e-15  7.37578840e-01]
 [-5.21546999e-01 -7.07106781e-01  4.77481651e-01]]


##### Нормы собственных векторов

In [2]:
m = len(eigenvalues)

for i in range(m):
    print(f'Норма собственного вектора для λ = {eigenvalues[i]}, есть {np.dot(eigenvectors[:, i], eigenvectors[:, i])}')

Норма собственного вектора для λ = 137.17890834580027, есть 0.9999999999999999
Норма собственного вектора для λ = 129.99999999999991, есть 1.0000000000000002
Норма собственного вектора для λ = 125.82109165419973, есть 1.0000000000000004


##### Проверим найденные собственные значения

$$A \cdot x = \lambda \cdot x$$

$$(A - \lambda I) \cdot x = 0$$

In [3]:
n = len(eigenvectors[0])

for i in range(m):
    b = np.diag([eigenvalues[i]] * n)
    c = a - b

    print('---')
    print(f'Проверка собственного значения λ = {eigenvalues[i]}')
    print(f'Детерминант матрицы A - λI = {np.linalg.det(c)}')
    print(f'(A - λI)x = {np.dot(c, eigenvectors[:, i])}')

---
Проверка собственного значения λ = 137.17890834580027
Детерминант матрицы A - λI = 5.866059352165318e-13
(A - λI)x = [-2.93098879e-14 -2.04281037e-14 -1.06581410e-14]
---
Проверка собственного значения λ = 129.99999999999991
Детерминант матрицы A - λI = -2.5579538487363457e-12
(A - λI)x = [ 8.38027766e-14 -5.07457138e-17 -3.67674439e-14]
---
Проверка собственного значения λ = 125.82109165419973
Детерминант матрицы A - λI = -3.414686913792975e-13
(A - λI)x = [ 5.01820807e-14 -3.15303339e-14 -1.59872116e-14]
