# Итерационные методы решения СЛАУ

### 1. Метод Гаусса-Зейделя

In [1]:
import sys
sys.path.append('..')

In [2]:
import numpy as np
from modules.slae.solver.iterative.gauss_seidel import gauss_seidel

a = np.array([
    [7., -3., 1.],
    [-3., 7., -3.],
    [1., -3., 7.]
])

b = np.array([2., -2., 2.])

x, iter = gauss_seidel(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 17


array([ 0.21052632, -0.10526316,  0.21052632])

##### Проверим найденное решение

Если $x$ решение $A * x = b$, то $r = A * x - b = 0$

In [3]:
r = np.dot(a, x) - b

r

array([-4.08008294e-10, -9.23314758e-11,  0.00000000e+00])

### 2. Метод Гаусса-Зейделя c релаксацией

In [4]:
from modules.slae.solver.iterative.gauss_seidel import gauss_seidel_relax

a = np.array([
    [7., -3., -1.],
    [-3., 7., -3.],
    [1., -3., 7.]
])

b = np.array([-2., 2., 2.])

x, iter = gauss_seidel_relax(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 16


array([2.96360116e-10, 5.00000000e-01, 5.00000000e-01])

In [5]:
r = np.dot(a, x) - b

r

array([ 1.67074043e-09,  2.45345966e-11, -6.46109832e-11])

### 3. Метод сопряженных градиентов

In [6]:
from modules.slae.solver.iterative.conjugate_gradient import conjugate_gradient

a = np.array([
    [7., -3., 1.],
    [-3., 7., -3.],
    [1., -3., 7.]
])

b = np.array([-2., 2., 2.])

x, iter = conjugate_gradient(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 3


array([-0.1754386 ,  0.42105263,  0.49122807])

In [7]:
r = np.dot(a, x) - b

r

array([ 4.44089210e-16, -2.22044605e-16,  0.00000000e+00])

### 4. Метод сопряженных градиентов для разреженной матрицы

In [8]:
from modules.slae.solver.iterative.conjugate_gradient import conjugate_gradient_sym_triplet

t = [
    [0, 0, 7.],
    [0, 1, -3.],
    [0, 2, 1.],
    [1, 1, 7.],
    [1, 2, -3.],
    [2, 2, 7.],
]

b = np.array([-2., 2., 2.])

x, iter = conjugate_gradient_sym_triplet(t, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 3


array([-0.1754386 ,  0.42105263,  0.49122807])

In [9]:
from modules.matrix.utils import matrix_sym_triplet_mult_vector

r = matrix_sym_triplet_mult_vector(t, x) - b

r

array([0., 0., 0.])