# Собственные значения и вектора матрицы

### Пример №1

##### Нахождение собственного значения и вектора матрицы

In [2]:
import numpy as np

a = np.array([[7, -3, 1], [-3, 7, -3], [1, -3, 7]])

eigenvalues, eigenvectors = np.linalg.eig(a)

print("Собственные значения:")
print(eigenvalues)

print("\nСобственные векторы:")
print(eigenvectors)

Собственные значения:
[11.77200187  6.          3.22799813]

Собственные векторы:
[[-5.28450837e-01  7.07106781e-01  4.69829451e-01]
 [ 6.64439182e-01 -2.57243434e-16  7.47342340e-01]
 [-5.28450837e-01 -7.07106781e-01  4.69829451e-01]]


##### Нормы собственных векторов

In [3]:
m = len(eigenvalues)

for i in range(m):
    print(f'Норма собственного вектора для λ = {eigenvalues[i]}, есть {np.dot(eigenvectors[:, i], eigenvectors[:, i])}')

Норма собственного вектора для λ = 11.772001872658768, есть 1.0000000000000002
Норма собственного вектора для λ = 5.999999999999998, есть 1.0
Норма собственного вектора для λ = 3.2279981273412353, есть 0.9999999999999998


##### Проверим найденные собственные значения

$$A \cdot x = \lambda \cdot x$$

$$(A - \lambda I) \cdot x = 0$$

In [4]:
n = len(eigenvectors[0])

for i in range(m):
    b = np.diag([eigenvalues[i]] * n)
    c = a - b

    print('---')
    print(f'Проверка собственного значения λ = {eigenvalues[i]}')
    print(f'Детерминант матрицы A - λI = {np.linalg.det(c)}')
    print(f'(A - λI)x = {np.dot(c, eigenvectors[:, i])}')

---
Проверка собственного значения λ = 11.772001872658768
Детерминант матрицы A - λI = -9.996806628440212e-14
(A - λI)x = [ 2.22044605e-16 -1.77635684e-15  1.33226763e-15]
---
Проверка собственного значения λ = 5.999999999999998
Детерминант матрицы A - λI = -2.8421709430404045e-14
(A - λI)x = [ 1.43786412e-15  1.07502420e-15 -1.00462654e-15]
---
Проверка собственного значения λ = 3.2279981273412353
Детерминант матрицы A - λI = -1.47721934559831e-14
(A - λI)x = [ 0.0000000e+00 -8.8817842e-16  0.0000000e+00]
