# Итерационные методы решения СЛАУ

### 1. Метод Гаусса-Зейделя

In [11]:
import sys
sys.path.append('..')

In [12]:
import numpy as np
from modules.slae.solver.iterative.gauss_seidel import gauss_seidel

a = np.array([
    [7., -3., 1.],
    [-3., 7., -3.],
    [1., -3., 7.]
])

b = np.array([-2., 2., 2.])

x, iter = gauss_seidel(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 17


array([-0.1754386 ,  0.42105263,  0.49122807])

##### Проверим найденное решение

Если $x$ решение $A * x = b$, то $r = A * x - b = 0$

In [13]:
r = np.dot(a, x) - b

r

array([-1.28170630e-09, -2.90048874e-10,  4.44089210e-16])

### 2. Метод Гаусса-Зейделя c релаксацией

In [14]:
from modules.slae.solver.iterative.gauss_seidel import gauss_seidel_relax

a = np.array([
    [7., -3., 1.],
    [-3., 7., -3.],
    [1., -3., 7.]
])

b = np.array([-2., 2., 2.])

x, iter = gauss_seidel_relax(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 16


array([-0.1754386 ,  0.42105263,  0.49122807])

In [15]:
r = np.dot(a, x) - b

r

array([ 3.29988925e-10,  5.15276710e-11, -1.87365679e-11])

### 3. Метод сопряженных градиентов

In [16]:
from modules.slae.solver.iterative.conjugate_gradient import conjugate_gradient

a = np.array([
    [7., -3., 1.],
    [-3., 7., -3.],
    [1., -3., 7.]
])

b = np.array([-2., 2., 2.])

x, iter = conjugate_gradient(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 3


array([-0.1754386 ,  0.42105263,  0.49122807])

In [17]:
r = np.dot(a, x) - b

r

array([-4.4408921e-16,  4.4408921e-16,  4.4408921e-16])

### 4. Метод сопряженных градиентов для разреженной матрицы

In [18]:
from modules.slae.solver.iterative.conjugate_gradient import conjugate_gradient_sym_triplet

t = [
    [0, 0, 7.],
    [0, 1, -3.],
    [0, 2, 1.],
    [1, 1, 7.],
    [1, 2, -3.],
    [2, 2, 7.],
]

b = np.array([-2., 2., 2.])

x, iter = conjugate_gradient_sym_triplet(t, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 3


array([-0.1754386 ,  0.42105263,  0.49122807])

In [19]:
from modules.matrix.utils import matrix_sym_triplet_mult_vector

r = matrix_sym_triplet_mult_vector(t, x) - b

r

array([0., 0., 0.])