# Итерационные методы решения СЛАУ

In [1]:
import sys

sys.path.append('..')

### 1. Метод Гаусса-Зейделя

In [2]:
import numpy as np
from modules.slae.solver.iterative.gauss_seidel import gauss_seidel

a = np.array([
    [13, -4., 1.],
    [-4., 13., -4.],
    [1., -4., 13.]
])

b = np.array([-112., 661., -113.])

x, iter = gauss_seidel(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 14


array([ 7.91833333, 55.69333333,  7.835     ])

##### Проверим найденное решение

Если $x$ решение $A * x = b$, то $r = A * x - b = 0$

In [3]:
r = np.dot(a, x) - b

r

array([-8.01392730e-10, -1.13118404e-10,  0.00000000e+00])

### 2. Метод Гаусса-Зейделя c релаксацией

In [4]:
from modules.slae.solver.iterative.gauss_seidel import gauss_seidel_relax

a = np.array([
    [13, -4., 1.],
    [-4., 13., -4.],
    [1., -4., 13.]
])

b = np.array([-112., 661., -113.])


x, iter = gauss_seidel_relax(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 14


array([ 7.91833333, 55.69333333,  7.835     ])

In [5]:
r = np.dot(a, x) - b

r

array([-9.23989774e-11,  3.81987775e-11, -1.90425453e-12])

### 3. Метод сопряженных градиентов

In [6]:
from modules.slae.solver.iterative.conjugate_gradient import conjugate_gradient

a = np.array([
    [13, -4., 1.],
    [-4., 13., -4.],
    [1., -4., 13.]
])

b = np.array([-112., 661., -113.])


x, iter = conjugate_gradient(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 3


array([ 7.91833333, 55.69333333,  7.835     ])

In [7]:
r = np.dot(a, x) - b

r

array([ 4.26325641e-14, -1.13686838e-13,  4.26325641e-14])

### 4. Метод сопряженных градиентов для разреженной матрицы

In [8]:
from modules.slae.solver.iterative.conjugate_gradient import conjugate_gradient_sym_triplet

t = [
    [0, 0, 13.],
    [0, 1, -4.],
    [0, 2, 1.],
    [1, 1, 13.],
    [1, 2, -4.],
    [2, 2, 13.]
]

b = np.array([-112., 661., -113.])

x, iter = conjugate_gradient_sym_triplet(t, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 3


array([ 7.91833333, 55.69333333,  7.835     ])

In [9]:
from modules.matrix.utils import matrix_sym_triplet_mult_vector

r = matrix_sym_triplet_mult_vector(t, x) - b

r

array([5.68434189e-14, 0.00000000e+00, 5.68434189e-14])