# Собственные значения и вектора матрицы

##### Нахождение собственного значения и вектора матрицы

In [2]:
import numpy as np

a = np.array([[12, -3, 1], [-3, 12, -3], [1, -3, 12]])

eigenvalues, eigenvectors = np.linalg.eig(a)

print("Собственные значения:")
print(eigenvalues)

print("\nСобственные векторы:") 
print(eigenvectors)

Собственные значения:
[16.77200187 11.          8.22799813]

Собственные векторы:
[[-5.28450837e-01  7.07106781e-01  4.69829451e-01]
 [ 6.64439182e-01  5.71877581e-16  7.47342340e-01]
 [-5.28450837e-01 -7.07106781e-01  4.69829451e-01]]


##### Нормы собственных векторов

In [3]:
m = len(eigenvalues)

for i in range(m):
    print(f'Норма собственного вектора для λ = {eigenvalues[i]}, есть {np.dot(eigenvectors[:, i], eigenvectors[:, i])}')

Норма собственного вектора для λ = 16.772001872658777, есть 0.9999999999999998
Норма собственного вектора для λ = 10.999999999999998, есть 0.9999999999999999
Норма собственного вектора для λ = 8.227998127341236, есть 0.9999999999999998


##### Проверим найденные собственные значения

$$A \cdot x = \lambda \cdot x$$

$$(A - \lambda I) \cdot x = 0$$

In [5]:
n = len(eigenvectors[0])

for i in range(m):
    b = np.diag([eigenvalues[i]] * n)
    c = a - b

    print('---')
    print(f'Проверка собственного значения λ = {eigenvalues[i]}')
    print(f'Детерминант матрицы A - λI = {np.linalg.det(c)}')
    print(f'(A - λI)x = {np.dot(c, eigenvectors[:, i])}')

---
Проверка собственного значения λ = 16.772001872658777
Детерминант матрицы A - λI = -5.38289587685246e-13
(A - λI)x = [ 5.55111512e-15 -9.88098492e-15  2.91385894e-15]
---
Проверка собственного значения λ = 10.999999999999998
Детерминант матрицы A - λI = -2.8421709430404045e-14
(A - λI)x = [ 4.44089210e-16 -2.22044605e-15 -2.03323008e-15]
---
Проверка собственного значения λ = 8.227998127341236
Детерминант матрицы A - λI = -3.693048363995778e-14
(A - λI)x = [-2.77555756e-16 -2.33146835e-15  1.07817621e-15]
