# Итерационные методы решения СЛАУ

In [2]:
import sys

sys.path.append('..')

### 1. Метод Гаусса-Зейделя

In [3]:
import numpy as np
from modules.slae.solver.iterative.gauss_seidel import gauss_seidel

a = np.array([
    [11., -4., 1.],
    [-4., 11., -4.],
    [1., -4., 11.]
])

b = np.array([7., 7., 7.])

x, iter = gauss_seidel(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 15


array([1.05, 1.4 , 1.05])

##### Проверим найденное решение

Если $x$ решение $A * x = b$, то $r = A * x - b = 0$

In [4]:
r = np.dot(a, x) - b

r

array([-1.67663483e-09, -3.67113451e-10,  0.00000000e+00])

### 2. Метод Гаусса-Зейделя c релаксацией

In [5]:
from modules.slae.solver.iterative.gauss_seidel import gauss_seidel_relax

a = np.array([
   [11., -4., 1.],
    [-4., 11., -4.],
    [1., -4., 11.]
])

b = np.array([7., 7., 7.])

x, iter = gauss_seidel_relax(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 15


array([1.05, 1.4 , 1.05])

In [6]:
r = np.dot(a, x) - b

r

array([ 3.13882254e-12,  3.62634367e-11, -3.85114163e-12])

### 3. Метод сопряженных градиентов

In [7]:
from modules.slae.solver.iterative.conjugate_gradient import conjugate_gradient

a = np.array([
    [11., -4., 1.],
    [-4., 11., -4.],
    [1., -4., 11.]
])

b = np.array([7., 7., 7.])

x, iter = conjugate_gradient(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 2


array([1.05, 1.4 , 1.05])

In [8]:
r = np.dot(a, x) - b

r

array([-1.77635684e-15,  0.00000000e+00, -1.77635684e-15])

### 4. Метод сопряженных градиентов для разреженной матрицы

In [9]:
from modules.slae.solver.iterative.conjugate_gradient import conjugate_gradient_sym_triplet

t = [
    [0, 0, 11.],
    [0, 1, -4.],
    [0, 2,  1.],
    [1, 1, 11.],
    [1, 2, -4.],
    [2, 2, 11.],
]

b = np.array([7., 7., 7.])

x, iter = conjugate_gradient_sym_triplet(t, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 2


array([1.05, 1.4 , 1.05])

In [10]:
from modules.matrix.utils import matrix_sym_triplet_mult_vector

r = matrix_sym_triplet_mult_vector(t, x) - b

r

array([-2.66453526e-15,  0.00000000e+00, -2.66453526e-15])