# Собственные значения и вектора матрицы

### Пример №1

##### Нахождение собственного значения и вектора матрицы

In [1]:
import numpy as np

a = np.array([[12, -4, 1], [-4, 12, -4], [1, -4, 12]])

eigenvalues, eigenvectors = np.linalg.eig(a)

print("Собственные значения:")
print(eigenvalues)

print("\nСобственные векторы:")
print(eigenvectors)

Собственные значения:
[18.17890835 11.          6.82109165]

Собственные векторы:
[[-5.21546999e-01  7.07106781e-01  4.77481651e-01]
 [ 6.75261027e-01  5.99110536e-17  7.37578840e-01]
 [-5.21546999e-01 -7.07106781e-01  4.77481651e-01]]


##### Нормы собственных векторов

In [9]:
m = len(eigenvalues)

for i in range(m):
    print(f'Норма собственного вектора для λ = {eigenvalues[i]}, есть {np.dot(eigenvectors[:, i], eigenvectors[:, i])}')

Норма собственного вектора для λ = 18.17890834580028, есть 0.9999999999999999
Норма собственного вектора для λ = 11.000000000000002, есть 1.0
Норма собственного вектора для λ = 6.821091654199728, есть 1.0


##### Проверим найденные собственные значения

$$A \cdot x = \lambda \cdot x$$

$$(A - \lambda I) \cdot x = 0$$

In [10]:
n = len(eigenvectors[0])

for i in range(m):
    b = np.diag([eigenvalues[i]] * n)
    c = a - b

    print('---')
    print(f'Проверка собственного значения λ = {eigenvalues[i]}')
    print(f'Детерминант матрицы A - λI = {np.linalg.det(c)}')
    print(f'(A - λI)x = {np.dot(c, eigenvectors[:, i])}')

---
Проверка собственного значения λ = 18.17890834580028
Детерминант матрицы A - λI = -5.866059352165339e-13
(A - λI)x = [ 1.33226763e-15 -7.10542736e-15  2.66453526e-15]
---
Проверка собственного значения λ = 11.000000000000002
Детерминант матрицы A - λI = 5.329070518200769e-14
(A - λI)x = [-2.23804566e-15  3.16853552e-15  2.04444996e-16]
---
Проверка собственного значения λ = 6.821091654199728
Детерминант матрицы A - λI = -8.907878905546918e-14
(A - λI)x = [-1.33226763e-15 -4.44089210e-16 -1.77635684e-15]
