# Прямые методы решения СЛАУ

In [2]:
import sys

sys.path.append('..')

### 1. Метод Гаусса

##### Пример №1

In [4]:
import numpy as np
from modules.slae.solver.direct.gauss_elimination import gauss_elimination

a = np.array([
    [13., -4., 1.],
    [-4., 13., -4.],
    [1.,  -4., 13.]
])

b = np.array([-112., 661., -113.])

x = gauss_elimination(np.copy(a), np.copy(b))

x

array([ 7.91833333, 55.69333333,  7.835     ])

##### Проверим найденное решение

Если $x$ решение $A * x = b$, то $r = A * x - b = 0$

In [5]:
r = np.dot(a, x) - b

r

array([-1.42108547e-14,  0.00000000e+00, -1.42108547e-14])

In [6]:
r = np.dot(a, x) - b

r

array([-1.42108547e-14,  0.00000000e+00, -1.42108547e-14])

### 2. LU разложение

##### Пример №1

In [7]:
from modules.slae.solver.direct.lu_decomposition import lu_decomposition, lu_solve

a = np.array([
    [13., -4., 1.],
    [-4., 13., -4.],
    [1.,  -4., 13.]
])

lu = lu_decomposition(a.copy())

b = np.array([-112., 661., -113.])

x = lu_solve(lu, b.copy())

x

array([ 7.91833333, 55.69333333,  7.835     ])

In [8]:
r = np.dot(a, x) - b

r

array([-1.42108547e-14,  0.00000000e+00, -1.42108547e-14])

### 3. Разложение Холецкого

##### Пример №1

In [9]:
from modules.slae.solver.direct.choleski_decomposition import choleski_decomposition, choleski_solve

a = np.array([
    [13., -4., 1.],
    [-4., 13., -4.],
    [1.,  -4., 13.]
])

chol = choleski_decomposition(a.copy())

b = np.array([-112., 661., -113.])

x = choleski_solve(chol, b.copy())

x

array([ 7.91833333, 55.69333333,  7.835     ])

In [10]:
r = np.dot(a, x) - b

r

array([ 0.00000000e+00,  0.00000000e+00, -1.42108547e-14])

### 4. Трехдиагональная матрица

In [11]:
from modules.slae.solver.direct.lu_decomposition import lu_3_diag_decomposition, lu_3_diag_solve

a = np.array([
    [19., -4., 0., 0., 0.],
    [-4., 19., -4., 0, 0.],
    [0.,  -4., 19., -4, 0],
    [0., 0., -4., 19., -4],
    [0., 0., 0., -4., 19.]
])
d = np.ones((5)) * 5.
c = np.ones((4)) * (-1)

b = np.array([1115., 6664., 3333., 6662., 5551.])

e = c.copy()

ct, dt, et = lu_3_diag_decomposition(c.copy(), d.copy(), e.copy())
x = lu_3_diag_solve(ct, dt, et, b.copy())

x

array([ 568.0219697 , 1725.10984848, 1393.52727273, 1909.52651515,
       1492.10530303])

##### Проверим найденное решение

Если $x$ решение $A * x = b$, то $r = A * x - b = 0$

In [12]:
from modules.matrix.utils import matrix_3_diag_mult_vector

r = matrix_3_diag_mult_vector(c, d, e, x) - b

r

array([2.27373675e-13, 1.81898940e-12, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00])