# Собственные значения и вектора матрицы

### Пример №1

##### Нахождение собственного значения и вектора матрицы

In [1]:
import numpy as np

a = np.array([[6, -3, 1], [-3, 3, -3], [1, -3, 6]])

eigenvalues, eigenvectors = np.linalg.eig(a)

print("Собственные значения:")
print(eigenvalues)

print("\nСобственные векторы:")
print(eigenvectors)

Собственные значения:
[9.69041576 5.         0.30958424]

Собственные векторы:
[[-5.97160245e-01  7.07106781e-01  3.78681452e-01]
 [ 5.35536445e-01 -5.93997113e-17  8.44512117e-01]
 [-5.97160245e-01 -7.07106781e-01  3.78681452e-01]]


##### Нормы собственных векторов

In [2]:
m = len(eigenvalues)

for i in range(m):
    print(f'Норма собственного вектора для λ = {eigenvalues[i]}, есть {np.dot(eigenvectors[:, i], eigenvectors[:, i])}')

Норма собственного вектора для λ = 9.690415759823427, есть 1.0000000000000002
Норма собственного вектора для λ = 5.000000000000002, есть 1.0
Норма собственного вектора для λ = 0.3095842401765702, есть 1.0000000000000002


##### Проверим найденные собственные значения

$$A \cdot x = \lambda \cdot x$$

$$(A - \lambda I) \cdot x = 0$$

In [3]:
n = len(eigenvectors[0])

for i in range(m):
    b = np.diag([eigenvalues[i]] * n)
    c = a - b

    print('---')
    print(f'Проверка собственного значения λ = {eigenvalues[i]}')
    print(f'Детерминант матрицы A - λI = {np.linalg.det(c)}')
    print(f'(A - λI)x = {np.dot(c, eigenvectors[:, i])}')

---
Проверка собственного значения λ = 9.690415759823427
Детерминант матрицы A - λI = 1.1148710939198295e-13
(A - λI)x = [-5.66213743e-15 -2.44249065e-15 -9.08790359e-16]
---
Проверка собственного значения λ = 5.000000000000002
Детерминант матрицы A - λI = 4.030109579389327e-14
(A - λI)x = [-6.66133815e-16 -1.22124533e-15  1.92220778e-15]
---
Проверка собственного значения λ = 0.3095842401765702
Детерминант матрицы A - λI = 0.0
(A - λI)x = [2.77555756e-16 0.00000000e+00 5.04693258e-16]
