# Итерационные методы решения СЛАУ
# Задание №3

In [1]:
import sys

sys.path.append('..')

### 1. Метод Гаусса-Зейделя

In [2]:
import numpy as np
from modules.slae.solver.iterative.gauss_seidel import gauss_seidel

a = np.array([
    [7., -3., 1.],
    [-3., 7., -3.],
    [1., -3., 7.]
])

b = np.array([-11., 16., 26.])

x, iter = gauss_seidel(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 19


array([-0.43859649,  4.55263158,  5.72807018])

##### Проверим найденное решение

Если $x$ решение $A * x = b$, то $r = A * x - b = 0$

In [3]:
r = np.dot(a, x) - b

r

array([-1.00586917e-09, -2.27625918e-10,  0.00000000e+00])

### 2. Метод Гаусса-Зейделя c релаксацией

In [4]:
from modules.slae.solver.iterative.gauss_seidel import gauss_seidel_relax

a = np.array([
    [7., -3., 1.],
    [-3., 7., -3.],
    [1., -3., 7.]
])

b = np.array([-11., 16., 26.])

x, iter = gauss_seidel_relax(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 17


array([-0.43859649,  4.55263158,  5.72807018])

In [5]:
r = np.dot(a, x) - b

r

array([ 7.51251505e-10, -4.74198458e-11, -2.12381224e-11])

# Задание №4
### 3. Метод сопряженных градиентов

In [6]:
from modules.slae.solver.iterative.conjugate_gradient import conjugate_gradient

a = np.array([
    [7., -3., 1.],
    [-3., 7., -3.],
    [1., -3., 7.]
])

b = np.array([-11., 16., 26.])

x, iter = conjugate_gradient(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 3


array([-0.43859649,  4.55263158,  5.72807018])

In [7]:
r = np.dot(a, x) - b

r

array([0.00000000e+00, 3.55271368e-15, 0.00000000e+00])

### 4. Метод сопряженных градиентов для разреженной матрицы

In [8]:
from modules.slae.solver.iterative.conjugate_gradient import conjugate_gradient_sym_triplet

t = [
    [0, 0, 7.],
    [0, 1, -3.],
    [0, 2, 1.],
    [1, 1, 7.],
    [1, 2, -3.],
    [2, 2, 7.]
]

b = np.array([-11., 16., 26.])

x, iter = conjugate_gradient_sym_triplet(t, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 3


array([-0.43859649,  4.55263158,  5.72807018])

In [9]:
from modules.matrix.utils import matrix_sym_triplet_mult_vector

r = matrix_sym_triplet_mult_vector(t, x) - b

r

array([ 0.00000000e+00, -3.55271368e-15,  3.55271368e-15])