# Итерационные методы решения СЛАУ

In [1]:
import sys

sys.path.append('..')

### 1. Метод Гаусса-Зейделя

In [2]:
import numpy as np
from modules.slae.solver.iterative.gauss_seidel import gauss_seidel

a = np.array([
    [131., -4., 1.],
    [-4., 131., -4.],
    [1., -4., 131.]
])

b = np.array([-1111., 6666., -1111.])

x, iter = gauss_seidel(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

ModuleNotFoundError: No module named 'numpy'

##### Проверим найденное решение

Если $x$ решение $A * x = b$, то $r = A * x - b = 0$

In [14]:
r = np.dot(a, x) - b

r

NameError: name 'np' is not defined

### 2. Метод Гаусса-Зейделя c релаксацией

In [3]:
from modules.slae.solver.iterative.gauss_seidel import gauss_seidel_relax

a = np.array([
    [131., -4., 1.],
    [-4., 131., -4.],
    [1., -4., 131.]
])

b = np.array([-1111., 6666., -1111.])

x, iter = gauss_seidel_relax(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

ModuleNotFoundError: No module named 'numpy'

In [5]:
r = np.dot(a, x) - b

r

array([ 9.97992800e-11,  2.38632225e-10, -2.16822116e-11])

### 3. Метод сопряженных градиентов

In [6]:
from modules.slae.solver.iterative.conjugate_gradient import conjugate_gradient

a = np.array([
    [131., -4., 1.],
    [-4., 131., -4.],
    [1., -4., 131.]
])

b = np.array([-1111., 6666., -1111.])

x, iter = conjugate_gradient(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 3


array([3., 1., 1.])

In [7]:
r = np.dot(a, x) - b

r

array([ 1.77635684e-15, -8.88178420e-16,  1.77635684e-15])

### 4. Метод сопряженных градиентов для разреженной матрицы

In [8]:
from modules.slae.solver.iterative.conjugate_gradient import conjugate_gradient_sym_triplet

t = [
    [0, 0, 131.],
    [0, 1, -4.],
    [0, 2, 1.],
    [1, 1, 131.],
    [1, 2, -4.],
    [2, 2, 131]
]

b = np.array([4., 10., -10.])

x, iter = conjugate_gradient_sym_triplet(t, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 3


array([ 0.54464286,  1.06696429, -0.73214286])

In [9]:
from modules.matrix.utils import matrix_sym_triplet_mult_vector

r = matrix_sym_triplet_mult_vector(t, x) - b

r

array([-8.88178420e-16, -1.77635684e-15,  3.55271368e-15])