# Собственные значения и вектора матрицы

##### Нахождение собственного значения и вектора матрицы

In [8]:
import numpy as np

a = np.array([[9, -4, 1], [-4, 9, -4], [1, -4, 9]])

eigenvalues, eigenvectors = np.linalg.eig(a)

print("Собственные значения:")
print(eigenvalues)

print("\nСобственные векторы:")
print(eigenvectors)

Собственные значения:
[15.17890835  8.          3.82109165]

Собственные векторы:
[[-5.21546999e-01  7.07106781e-01  4.77481651e-01]
 [ 6.75261027e-01 -3.54867315e-16  7.37578840e-01]
 [-5.21546999e-01 -7.07106781e-01  4.77481651e-01]]


##### Нормы собственных векторов

In [14]:
m = len(eigenvalues)

for i in range(m):
    print(f'Норма собственного вектора для λ = {eigenvalues[i]}, есть {np.dot(eigenvectors[:, i], eigenvectors[:, i])}')

Норма собственного вектора для λ = 2.999999999999999, есть 1.0
Норма собственного вектора для λ = 0.9999999999999998, есть 0.9999999999999999
Норма собственного вектора для λ = -3.367702055640532e-17, есть 0.9999999999999999


##### Проверим найденные собственные значения

$$A \cdot x = \lambda \cdot x$$

$$(A - \lambda I) \cdot x = 0$$

In [15]:
n = len(eigenvectors[0])

for i in range(m):
    b = np.diag([eigenvalues[i]] * n)
    c = a - b

    print('---')
    print(f'Проверка собственного значения λ = {eigenvalues[i]}')
    print(f'Детерминант матрицы A - λI = {np.linalg.det(c)}')
    print(f'(A - λI)x = {np.dot(c, eigenvectors[:, i])}')

---
Проверка собственного значения λ = 2.999999999999999
Детерминант матрицы A - λI = 5.329070518200744e-15
(A - λI)x = [-1.13975344e-15  4.99600361e-16 -1.40552717e-16]
---
Проверка собственного значения λ = 0.9999999999999998
Детерминант матрицы A - λI = -4.4408920985006143e-16
(A - λI)x = [-4.18248792e-16  0.00000000e+00 -1.04230301e-16]
---
Проверка собственного значения λ = -3.367702055640532e-17
Детерминант матрицы A - λI = 0.0
(A - λI)x = [-1.11022302e-16  3.33066907e-16 -2.22044605e-16]
