# Собственные значения и вектора матрицы

##### Нахождение собственного значения и вектора матрицы

In [2]:
import numpy as np

a = np.array([[11, -4, 1], [-4, 11, -4], [1, -4, -11]])

eigenvalues, eigenvectors = np.linalg.eig(a)

print("Собственные значения:")
print(eigenvalues)

print("\nСобственные векторы:")
print(eigenvectors)

Собственные значения:
[ 15.48167479   7.22687196 -11.70854676]

Собственные векторы:
[[ 0.67637566 -0.73643807 -0.01322633]
 [-0.72409536 -0.66811432  0.17119921]
 [ 0.13491432  0.10621785  0.98514765]]


##### Нормы собственных векторов

In [4]:
m = len(eigenvalues)

for i in range(m):
    print(f'Норма собственного вектора для λ = {eigenvalues[i]}, есть {np.dot(eigenvectors[:, i], eigenvectors[:, i])}')

Норма собственного вектора для λ = 15.481674794181043, есть 0.9999999999999997
Норма собственного вектора для λ = 7.226871963858953, есть 1.0
Норма собственного вектора для λ = -11.708546758039994, есть 1.0


##### Проверим найденные собственные значения

$$A \cdot x = \lambda \cdot x$$

$$(A - \lambda I) \cdot x = 0$$

In [5]:
n = len(eigenvectors[0])

for i in range(m):
    b = np.diag([eigenvalues[i]] * n)
    c = a - b

    print('---')
    print(f'Проверка собственного значения λ = {eigenvalues[i]}')
    print(f'Детерминант матрицы A - λI = {np.linalg.det(c)}')
    print(f'(A - λI)x = {np.dot(c, eigenvectors[:, i])}')

---
Проверка собственного значения λ = 15.481674794181043
Детерминант матрицы A - λI = 1.7527338921620644e-13
(A - λI)x = [ 5.38458167e-15  3.88578059e-15 -1.69522619e-15]
---
Проверка собственного значения λ = 7.226871963858953
Детерминант матрицы A - λI = 4.3981557465880845e-13
(A - λI)x = [ 1.41553436e-15  2.66453526e-15 -8.89042429e-16]
---
Проверка собственного значения λ = -11.708546758039994
Детерминант матрицы A - λI = 1.6642623807808412e-13
(A - λI)x = [ 1.11022302e-16 -4.44089210e-16  4.19853290e-16]
