# Задание №2

In [3]:
import sys

sys.path.append('..')

### 1. Метод Гаусса

In [4]:
import numpy as np
from modules.slae.solver.direct.gauss_elimination import gauss_elimination

a = np.array([
    [8., -4., 1.],
    [-4., 8., -4.],
    [1., -4., 8.]
])

b = np.array([-13., 14., 16.])

x = gauss_elimination(np.copy(a), np.copy(b))

x

array([-0.37142857,  3.45      ,  3.77142857])

##### Проверим найденное решение

Если $x$ решение $A * x = b$, то $r = A * x - b = 0$

In [5]:
r = np.dot(a, x) - b

r

array([0.00000000e+00, 1.77635684e-15, 0.00000000e+00])

### 2. LU разложение

In [9]:
from modules.slae.solver.direct.lu_decomposition import lu_decomposition, lu_solve

a = np.array([
    [8., -4., 1.],
    [-4., 8., -4.],
    [1., -4., 8.]
])

lu = lu_decomposition(a.copy())

b = np.array([-13., 14., 16.])

x = lu_solve(lu, b.copy())

x

array([-0.37142857,  3.45      ,  3.77142857])

In [10]:
r = np.dot(a, x) - b

r

array([0.00000000e+00, 1.77635684e-15, 0.00000000e+00])

### 3. Разложение Холецкого

In [11]:
from modules.slae.solver.direct.choleski_decomposition import choleski_decomposition, choleski_solve

a = np.array([
    [8., -4., 1.],
    [-4., 8., -4.],
    [1., -4., 8.]
])

chol = choleski_decomposition(a.copy())

b = np.array([-13., 14., 16.])

x = choleski_solve(chol, b.copy())

x

array([-0.37142857,  3.45      ,  3.77142857])

In [12]:
r = np.dot(a, x) - b

r

array([ 0.00000000e+00,  7.10542736e-15, -3.55271368e-15])

### 4. Трехдиагональная матрица

In [13]:
from modules.slae.solver.direct.lu_decomposition import lu_3_diag_decomposition, lu_3_diag_solve

d = np.ones((5)) * 5.
c = np.ones((4)) * (-2)

b = np.array([14., -1., 4., -15., 5.])

e = c.copy()

ct, dt, et = lu_3_diag_decomposition(c.copy(), d.copy(), e.copy())
x = lu_3_diag_solve(ct, dt, et, b.copy())

x

array([ 3.23809524,  1.0952381 ,  0.        , -3.0952381 , -0.23809524])

##### Проверим найденное решение

Если $x$ решение $A * x = b$, то $r = A * x - b = 0$

In [14]:
from modules.matrix.utils import matrix_3_diag_mult_vector

r = matrix_3_diag_mult_vector(c, d, e, x) - b

r

array([0., 0., 0., 0., 0.])