# Итерационные методы решения СЛАУ

In [2]:
import sys

sys.path.append('..')

### 1. Метод Гаусса-Зейделя

In [73]:
import numpy as np
from modules.slae.solver.iterative.gauss_seidel import gauss_seidel

a = np.array([
    [12., -4., 1.],
    [-4., 12., -4.],
    [1., -4., 12.]
])

b = np.array([-1., 51., 212.])

x, iter = gauss_seidel(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 16


array([ 2.17302053, 12.15322581, 21.53665689])

##### Проверим найденное решение

Если $x$ решение $A * x = b$, то $r = A * x - b = 0$

In [75]:
r = np.dot(a, x) - b

r

array([-3.37081474e-10, -5.99555960e-11, -2.84217094e-14])

### 2. Метод Гаусса-Зейделя c релаксацией

In [71]:
from modules.slae.solver.iterative.gauss_seidel import gauss_seidel_relax

a = np.array([
    [12., -4., 1.],
    [-4., 12., -4.],
    [1., -4., 12.]
])

b = np.array([-1., 51., 212.])

x, iter = gauss_seidel_relax(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 15


array([ 2.17302053, 12.15322581, 21.53665689])

In [72]:
r = np.dot(a, x) - b

r

array([ 5.16564569e-11,  4.42952341e-11, -5.40012479e-12])

### 3. Метод сопряженных градиентов

In [67]:
from modules.slae.solver.iterative.conjugate_gradient import conjugate_gradient

a = np.array([
    [12., -4., 1.],
    [-4., 12., -4.],
    [1., -4., 12.]
])

b = np.array([-1., 51., 212.])

x, iter = conjugate_gradient(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 3


array([ 2.17302053, 12.15322581, 21.53665689])

In [68]:
r = np.dot(a, x) - b

r

array([-7.10542736e-15,  2.84217094e-14,  5.68434189e-14])

### 4. Метод сопряженных градиентов для разреженной матрицы

In [33]:
from modules.slae.solver.iterative.conjugate_gradient import conjugate_gradient_sym_triplet

t = [
    [0, 0, 12.],
    [0, 1, -4.],
    [0, 2, 1.],
    [1, 1, 12.],
    [1, 2, -4.],
    [2, 2, 12.]
]

b = np.array([-1., 51., 212.])

x, iter = conjugate_gradient_sym_triplet(t, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 3


array([ 2.17302053, 12.15322581, 21.53665689])

In [51]:
from modules.matrix.utils import matrix_sym_triplet_mult_vector

r = matrix_sym_triplet_mult_vector(t, x) - b

r

array([-3.37081474e-10, -5.99555960e-11,  0.00000000e+00])