# Итерационные методы решения СЛАУ

In [1]:
import sys

sys.path.append('..')

### 1. Метод Гаусса-Зейделя

In [3]:
import numpy as np
from modules.slae.solver.iterative.gauss_seidel import gauss_seidel

a = np.array([
    [8., -4., 1.],
    [-4., 8., -4.],
    [1., -4., 8.]
])

b = np.array([4., 4., 4.])

x, iter = gauss_seidel(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 26


array([1.2, 1.7, 1.2])

##### Проверим найденное решение

Если $x$ решение $A * x = b$, то $r = A * x - b = 0$

In [5]:
r = np.dot(a, x) - b

r

array([-9.69674119e-10, -3.84226873e-10,  0.00000000e+00])

### 2. Метод Гаусса-Зейделя c релаксацией

In [7]:
from modules.slae.solver.iterative.gauss_seidel import gauss_seidel_relax

a = np.array([
    [8., -4., 1.],
    [-4., 8., -4.],
    [1., -4., 8.]
])

b = np.array([4., 4., 4.])

x, iter = gauss_seidel_relax(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 20


array([1.2, 1.7, 1.2])

In [8]:
r = np.dot(a, x) - b

r

array([ 3.42888384e-10, -6.78266332e-11, -2.03304040e-11])

### 3. Метод сопряженных градиентов

In [9]:
from modules.slae.solver.iterative.conjugate_gradient import conjugate_gradient

a = np.array([
    [8., -4., 1.],
    [-4., 8., -4.],
    [1., -4., 8.]
])

b = np.array([4., 4., 4.])

x, iter = conjugate_gradient(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 2


array([1.2, 1.7, 1.2])

In [10]:
r = np.dot(a, x) - b

r

array([0.0000000e+00, 8.8817842e-16, 0.0000000e+00])

### 4. Метод сопряженных градиентов для разреженной матрицы

In [15]:
from modules.slae.solver.iterative.conjugate_gradient import conjugate_gradient_sym_triplet

t = [
    [0, 0, 8.],
    [0, 1, -4.],
    [0, 2, 1.],
    [1, 1, 8.],
    [1, 2, -4.],
    [2, 2, 8.]
]

b = np.array([4., 4., 4.])

x, iter = conjugate_gradient_sym_triplet(t, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 2


array([1.2, 1.7, 1.2])

In [16]:
from modules.matrix.utils import matrix_sym_triplet_mult_vector

r = matrix_sym_triplet_mult_vector(t, x) - b

r

array([0.0000000e+00, 8.8817842e-16, 0.0000000e+00])