# Собственные значения и вектора матрицы

### Пример №1

##### Нахождение собственного значения и вектора матрицы

In [6]:
import numpy as np

a = np.array([[8, -3, 1], [-3, 8, -3], [1, -3, 8]])

eigenvalues, eigenvectors = np.linalg.eig(a)

print("Собственные значения:")
print(eigenvalues)

print("\nСобственные векторы:")
print(eigenvectors)

Собственные значения:
[12.77200187  7.          4.22799813]

Собственные векторы:
[[-5.28450837e-01  7.07106781e-01  4.69829451e-01]
 [ 6.64439182e-01 -6.96180863e-17  7.47342340e-01]
 [-5.28450837e-01 -7.07106781e-01  4.69829451e-01]]


##### Нормы собственных векторов

In [7]:
m = len(eigenvalues)

for i in range(m):
    print(f'Норма собственного вектора для λ = {eigenvalues[i]}, есть {np.dot(eigenvectors[:, i], eigenvectors[:, i])}')

Норма собственного вектора для λ = 12.772001872658763, есть 1.0000000000000002
Норма собственного вектора для λ = 6.999999999999997, есть 1.0
Норма собственного вектора для λ = 4.227998127341235, есть 0.9999999999999998


##### Проверим найденные собственные значения

$$A \cdot x = \lambda \cdot x$$

$$(A - \lambda I) \cdot x = 0$$

In [8]:
n = len(eigenvectors[0])

for i in range(m):
    b = np.diag([eigenvalues[i]] * n)
    c = a - b

    print('---')
    print(f'Проверка собственного значения λ = {eigenvalues[i]}')
    print(f'Детерминант матрицы A - λI = {np.linalg.det(c)}')
    print(f'(A - λI)x = {np.dot(c, eigenvectors[:, i])}')

---
Проверка собственного значения λ = 12.772001872658763
Детерминант матрицы A - λI = 1.5102039607276259e-13
(A - λI)x = [-2.99760217e-15  5.55111512e-16 -2.47668458e-15]
---
Проверка собственного значения λ = 6.999999999999997
Детерминант матрицы A - λI = -4.218847493575602e-14
(A - λI)x = [ 2.44249065e-15 -7.77156117e-16 -1.32899944e-15]
---
Проверка собственного значения λ = 4.227998127341235
Детерминант матрицы A - λI = -7.010124819996148e-15
(A - λI)x = [ 1.16573418e-15 -1.60982339e-15  4.73840634e-16]
