# Итерационные методы решения СЛАУ

In [11]:
import sys

sys.path.append('..')

### 1. Метод Гаусса-Зейделя

In [12]:
import numpy as np
from modules.slae.solver.iterative.gauss_seidel import gauss_seidel

a = np.array([
    [11., -4., 1.],
    [-4., 11., -4.],
    [1., -4., 11.]
])

b = np.array([-2., 1., 6.])

x, iter = gauss_seidel(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 15


array([-0.14,  0.28,  0.66])

##### Проверим найденное решение

Если $x$ решение $A * x = b$, то $r = A * x - b = 0$

In [13]:
r = np.dot(a, x) - b

r

array([-8.91509977e-10, -1.95203409e-10,  0.00000000e+00])

### 2. Метод Гаусса-Зейделя c релаксацией

In [14]:
from modules.slae.solver.iterative.gauss_seidel import gauss_seidel_relax

a = np.array([
    [11., -4., 1.],
    [-4., 11., -4.],
    [1., -4., 11.]
])


b = np.array([-2., 1., 6.])

x, iter = gauss_seidel_relax(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 15


array([-0.14,  0.28,  0.66])

In [15]:
r = np.dot(a, x) - b

r

array([ 1.67554859e-12,  1.92814653e-11, -2.04813944e-12])

### 3. Метод сопряженных градиентов

In [16]:
from modules.slae.solver.iterative.conjugate_gradient import conjugate_gradient

a = np.array([
    [11., -4., 1.],
    [-4., 11., -4.],
    [1., -4., 11.]
])


b = np.array([-2., 1., 6.])

x, iter = conjugate_gradient(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 3


array([-0.14,  0.28,  0.66])

In [17]:
r = np.dot(a, x) - b

r

array([0., 0., 0.])

### 4. Метод сопряженных градиентов для разреженной матрицы

In [18]:
from modules.slae.solver.iterative.conjugate_gradient import conjugate_gradient_sym_triplet

t = [
    [0, 0, 11.],
    [0, 1, -4.],
    [0, 2, 1.],
    [1, 1, 11.],
    [1, 2, -4.],
    [2, 2, 11.]
]

b = np.array([-2., 1., 6.])

x, iter = conjugate_gradient_sym_triplet(t, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 3


array([-0.14,  0.28,  0.66])

In [19]:
from modules.matrix.utils import matrix_sym_triplet_mult_vector

r = matrix_sym_triplet_mult_vector(t, x) - b

r

array([0.0000000e+00, 0.0000000e+00, 8.8817842e-16])