# Собственные значения и вектора матрицы

##### Нахождение собственного значения и вектора матрицы

In [1]:
import numpy as np

a = np.array([[11, -5, 1], [-5, 11, -5], [1, -5, 11]])
eigenvalues, eigenvectors = np.linalg.eig(a)

print("Собственные значения:")
print(eigenvalues)

print("\nСобственные векторы:")
print(eigenvectors)

Собственные значения:
[18.58872344 10.          4.41127656]

Собственные векторы:
[[-5.17333201e-01  7.07106781e-01  4.82043939e-01]
 [ 6.81713077e-01 -2.67339966e-17  7.31619628e-01]
 [-5.17333201e-01 -7.07106781e-01  4.82043939e-01]]


##### Нормы собственных векторов

In [2]:
m = len(eigenvalues)

for i in range(m):
    print(f'Норма собственного вектора для λ = {eigenvalues[i]}, есть {np.dot(eigenvectors[:, i], eigenvectors[:, i])}')

Норма собственного вектора для λ = 18.588723439378928, есть 1.0
Норма собственного вектора для λ = 10.000000000000004, есть 1.0
Норма собственного вектора для λ = 4.411276560621089, есть 0.9999999999999998


##### Проверим найденные собственные значения

$$A \cdot x = \lambda \cdot x$$

$$(A - \lambda I) \cdot x = 0$$

In [3]:
n = len(eigenvectors[0])

for i in range(m):
    b = np.diag([eigenvalues[i]] * n)
    c = a - b

    print('---')
    print(f'Проверка собственного значения λ = {eigenvalues[i]}')
    print(f'Детерминант матрицы A - λI = {np.linalg.det(c)}')
    print(f'(A - λI)x = {np.dot(c, eigenvectors[:, i])}')

---
Проверка собственного значения λ = 18.588723439378928
Детерминант матрицы A - λI = -1.8307965147909585e-12
(A - λI)x = [ 7.99360578e-15 -1.15463195e-14  6.21724894e-15]
---
Проверка собственного значения λ = 10.000000000000004
Детерминант матрицы A - λI = 1.705302565824236e-13
(A - λI)x = [-2.86393218e-15  2.19371205e-15  2.24309373e-15]
---
Проверка собственного значения λ = 4.411276560621089
Детерминант матрицы A - λI = -1.2409458881321551e-13
(A - λI)x = [-8.88178420e-16  8.88178420e-16 -2.22044605e-15]


### Пример №2

##### Нахождение собственного значения и вектора матрицы

In [4]:
a = np.array([[1, -1, 0], [-1, 2, -1], [0, -1, 1]])

eigenvalues, eigenvectors = np.linalg.eig(a)

print("Собственные значения:")
print(eigenvalues)

print("\nСобственные векторы:")
print(eigenvectors)

Собственные значения:
[ 3.00000000e+00  1.00000000e+00 -3.36770206e-17]

Собственные векторы:
[[-4.08248290e-01 -7.07106781e-01  5.77350269e-01]
 [ 8.16496581e-01  2.61239546e-16  5.77350269e-01]
 [-4.08248290e-01  7.07106781e-01  5.77350269e-01]]


##### Нормы собственных векторов

In [5]:
m = len(eigenvalues)

for i in range(m):
    print(f'Норма собственного вектора для λ = {eigenvalues[i]}, есть {np.dot(eigenvectors[:, i], eigenvectors[:, i])}')

Норма собственного вектора для λ = 2.999999999999999, есть 1.0
Норма собственного вектора для λ = 0.9999999999999998, есть 0.9999999999999999
Норма собственного вектора для λ = -3.367702055640532e-17, есть 0.9999999999999999


##### Проверим найденные собственные значения

$$A \cdot x = \lambda \cdot x$$

$$(A - \lambda I) \cdot x = 0$$

In [6]:
m = len(eigenvalues)
n = len(eigenvectors[0])

for i in range(m):
    b = np.diag([eigenvalues[i]] * n)
    c = a - b

    print('---')
    print(f'Проверка собственного значения λ = {eigenvalues[i]}')
    print(f'Детерминант матрицы A - λI = {np.linalg.det(c)}')
    print(f'(A - λI)x = {np.dot(c, eigenvectors[:, i])}')

---
Проверка собственного значения λ = 2.999999999999999
Детерминант матрицы A - λI = 5.329070518200744e-15
(A - λI)x = [-1.13975344e-15  4.99600361e-16 -1.40552717e-16]
---
Проверка собственного значения λ = 0.9999999999999998
Детерминант матрицы A - λI = -4.4408920985006143e-16
(A - λI)x = [-4.18248792e-16  0.00000000e+00 -1.04230301e-16]
---
Проверка собственного значения λ = -3.367702055640532e-17
Детерминант матрицы A - λI = 0.0
(A - λI)x = [-1.11022302e-16  3.33066907e-16 -2.22044605e-16]
