# Прямые методы решения СЛАУ

In [4]:
import sys

sys.path.append('..')

### 1. Метод Гаусса

In [6]:
import numpy as np
from modules.slae.solver.direct.gauss_elimination import gauss_elimination
a = np.array([
    [12., -4., 1.],
    [-4., 12., -4.],
    [1., -4., 12.]
])

b = np.array([1000., 1000., 1000.])

x = gauss_elimination(np.copy(a), np.copy(b))

x

array([129.03225806, 169.35483871, 129.03225806])

##### Проверим найденное решение

Если $x$ решение $A * x = b$, то $r = A * x - b = 0$

In [7]:
r = np.dot(a, x) - b

r

array([ 1.13686838e-13, -2.27373675e-13,  1.13686838e-13])

### 2. LU разложение

In [8]:
from modules.slae.solver.direct.lu_decomposition import lu_decomposition, lu_solve

a = np.array([
    [12., -4., 1.],
    [-4., 12., -4.],
    [1., -4., 12.]
])

lu = lu_decomposition(a.copy())

b = np.array([1000., 1000., 1000.])

x = lu_solve(lu, b.copy())

x

array([129.03225806, 169.35483871, 129.03225806])

In [9]:
r = np.dot(a, x) - b

r

array([ 1.13686838e-13, -2.27373675e-13,  1.13686838e-13])

### 3. Разложение Холецкого

In [10]:
from modules.slae.solver.direct.choleski_decomposition import choleski_decomposition, choleski_solve

a = np.array([
    [12., -4., 1.],
    [-4., 12., -4.],
    [1., -4., 12.]
])

chol = choleski_decomposition(a.copy())

b = np.array([1000., 1000., 1000.])

x = choleski_solve(chol, b.copy())

x

array([129.03225806, 169.35483871, 129.03225806])

In [11]:
r = np.dot(a, x) - b

r

array([2.27373675e-13, 0.00000000e+00, 0.00000000e+00])

### 4. Трехдиагональная матрица

In [12]:
from modules.slae.solver.direct.lu_decomposition import lu_3_diag_decomposition, lu_3_diag_solve

d = np.ones((5)) * 9.
c = np.ones((4)) * (-4)

b = np.array([1100., 2200., 3300., 4400., 5500.])

e = c.copy()

ct, dt, et = lu_3_diag_decomposition(c.copy(), d.copy(), e.copy())
x = lu_3_diag_solve(ct, dt, et, b.copy())

x

array([ 749.91452991, 1412.30769231, 1877.77777778, 1987.69230769,
       1494.52991453])

##### Проверим найденное решение

Если $x$ решение $A * x = b$, то $r = A * x - b = 0$

In [13]:
from modules.matrix.utils import matrix_3_diag_mult_vector

r = matrix_3_diag_mult_vector(c, d, e, x) - b

r

array([ 0.00000000e+00,  0.00000000e+00, -9.09494702e-13,  0.00000000e+00,
       -9.09494702e-13])