# Прямые методы решения СЛАУ

In [14]:
import sys

sys.path.append('..')

### 1. Метод Гаусса

In [15]:
import numpy as np
from modules.slae.solver.direct.gauss_elimination import gauss_elimination

a = np.array([
    [10., -4., 1.],
    [-4., 10., -4.],
    [1., -4., 10.]
])

b = np.array([-35., 41., 66.])

x = gauss_elimination(np.copy(a), np.copy(b))

x

array([-1.52136752,  7.37179487,  9.7008547 ])

##### Проверим найденное решение

Если $x$ решение $A * x = b$, то $r = A * x - b = 0$

In [16]:
r = np.dot(a, x) - b

r

array([-7.10542736e-15,  7.10542736e-15,  0.00000000e+00])

### 2. LU разложение

##### Пример №1

In [17]:
from modules.slae.solver.direct.lu_decomposition import lu_decomposition, lu_solve

a = np.array([
    [10., -4., 1.],
    [-4., 10., -4.],
    [1., -4., 10.]
])

lu = lu_decomposition(a.copy())

b = np.array([-35., 41., 66.])

x = lu_solve(lu, b.copy())

x

array([-1.52136752,  7.37179487,  9.7008547 ])

In [18]:
r = np.dot(a, x) - b

r

array([-7.10542736e-15,  7.10542736e-15,  0.00000000e+00])

### 3. Разложение Холецкого

##### Пример №1

In [19]:
from modules.slae.solver.direct.choleski_decomposition import choleski_decomposition, choleski_solve

a = np.array([
    [10., -4., 1.],
    [-4., 10., -4.],
    [1., -4., 10.]
])

chol = choleski_decomposition(a.copy())

b = np.array([-35., 41., 66.])

x = choleski_solve(chol, b.copy())

x

array([-1.52136752,  7.37179487,  9.7008547 ])

In [20]:
r = np.dot(a, x) - b

r

array([ 7.10542736e-15, -7.10542736e-15,  0.00000000e+00])

### 4. Трехдиагональная матрица

In [21]:
from modules.slae.solver.direct.lu_decomposition import lu_3_diag_decomposition, lu_3_diag_solve

d = np.ones((5)) * 7.
c = np.ones((4)) * (-2)

b = np.array([13., -21., 45., -32., 21.])

e = c.copy()

ct, dt, et = lu_3_diag_decomposition(c.copy(), d.copy(), e.copy())
x = lu_3_diag_solve(ct, dt, et, b.copy())

x

array([ 1.57589018, -0.98438438,  5.47876448, -2.33993994,  2.33144573])

##### Проверим найденное решение

Если $x$ решение $A * x = b$, то $r = A * x - b = 0$

In [22]:
from modules.matrix.utils import matrix_3_diag_mult_vector

r = matrix_3_diag_mult_vector(c, d, e, x) - b

r

array([ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
       -3.55271368e-15])