# Собственные значения и вектора матрицы

##### Нахождение собственного значения и вектора матрицы

In [1]:
import numpy as np

a = np.array([[13, -4, 1], [-4, 13, -4], [1, -4, 13]])

eigenvalues, eigenvectors = np.linalg.eig(a)

print("Собственные значения:")
print(eigenvalues)

print("\nСобственные векторы:")
print(eigenvectors)

Собственные значения:
[19.17890835 12.          7.82109165]

Собственные векторы:
[[-5.21546999e-01  7.07106781e-01  4.77481651e-01]
 [ 6.75261027e-01 -3.48719201e-16  7.37578840e-01]
 [-5.21546999e-01 -7.07106781e-01  4.77481651e-01]]


##### Нормы собственных векторов

In [2]:
m = len(eigenvalues)

for i in range(m):
    print(f'Норма собственного вектора для λ = {eigenvalues[i]}, есть {np.dot(eigenvectors[:, i], eigenvectors[:, i])}')

Норма собственного вектора для λ = 19.178908345800274, есть 0.9999999999999999
Норма собственного вектора для λ = 11.999999999999991, есть 1.0
Норма собственного вектора для λ = 7.8210916541997255, есть 1.0


##### Проверим найденные собственные значения

$$A \cdot x = \lambda \cdot x$$

$$(A - \lambda I) \cdot x = 0$$

In [3]:
n = len(eigenvectors[0])

for i in range(m):
    b = np.diag([eigenvalues[i]] * n)
    c = a - b

    print('---')
    print(f'Проверка собственного значения λ = {eigenvalues[i]}')
    print(f'Детерминант матрицы A - λI = {np.linalg.det(c)}')
    print(f'(A - λI)x = {np.dot(c, eigenvectors[:, i])}')

---
Проверка собственного значения λ = 19.178908345800274
Детерминант матрицы A - λI = 0.0
(A - λI)x = [-2.66453526e-15 -3.99680289e-15 -2.22044605e-15]
---
Проверка собственного значения λ = 11.999999999999991
Детерминант матрицы A - λI = -2.664535259100373e-13
(A - λI)x = [ 6.77236045e-15  3.55271368e-15 -5.88418203e-15]
---
Проверка собственного значения λ = 7.8210916541997255
Детерминант матрицы A - λI = 4.453939452773451e-14
(A - λI)x = [ 4.77395901e-15 -1.77635684e-15 -4.44089210e-16]
