# Задание №2

In [2]:
import sys

sys.path.append('..')

### 1. Метод Гаусса

In [3]:
import numpy as np
from modules.slae.solver.direct.gauss_elimination import gauss_elimination

a = np.array([
    [12., -3., 1.],
    [-3., 12., -3.],
    [1., -3., 12.]
])

b = np.array([-11., 5., 21.])

x = gauss_elimination(np.copy(a), np.copy(b))

x

array([-0.91106719,  0.6884058 ,  1.99802372])

##### Проверим найденное решение

Если $x$ решение $A * x = b$, то $r = A * x - b = 0$

In [4]:
r = np.dot(a, x) - b

r

array([0.00000000e+00, 0.00000000e+00, 3.55271368e-15])

### 2. LU разложение

In [5]:
from modules.slae.solver.direct.lu_decomposition import lu_decomposition, lu_solve

a = np.array([
    [12., -3., 1.],
    [-3., 12., -3.],
    [1., -3., 12.]
])

lu = lu_decomposition(a.copy())

b = np.array([-11., 5., 21.])

x = lu_solve(lu, b.copy())

x

array([-0.91106719,  0.6884058 ,  1.99802372])

In [6]:
r = np.dot(a, x) - b

r

array([0.0000000e+00, 8.8817842e-16, 0.0000000e+00])

### 3. Разложение Холецкого

In [7]:
from modules.slae.solver.direct.choleski_decomposition import choleski_decomposition, choleski_solve

a = np.array([
    [12., -3., 1.],
    [-3., 12., -3.],
    [1., -3., 12.]
])

chol = choleski_decomposition(a.copy())

b = np.array([-11., 5., 21.])

x = choleski_solve(chol, b.copy())

x

array([-0.91106719,  0.6884058 ,  1.99802372])

In [8]:
r = np.dot(a, x) - b

r

array([ 0.00000000e+00, -2.66453526e-15,  0.00000000e+00])

### 4. Трехдиагональная матрица

In [9]:
from modules.slae.solver.direct.lu_decomposition import lu_3_diag_decomposition, lu_3_diag_solve

d = np.ones((5)) * 8.
c = np.ones((4)) * (-4)

b = np.array([1., 2., 3., 4., 5.])

e = c.copy()

ct, dt, et = lu_3_diag_decomposition(c.copy(), d.copy(), e.copy())
x = lu_3_diag_solve(ct, dt, et, b.copy())

x

array([1.45833333, 2.66666667, 3.375     , 3.33333333, 2.29166667])

##### Проверим найденное решение

Если $x$ решение $A * x = b$, то $r = A * x - b = 0$

In [10]:
from modules.matrix.utils import matrix_3_diag_mult_vector

r = matrix_3_diag_mult_vector(c, d, e, x) - b

r

array([ 0.00000000e+00,  1.77635684e-15, -5.32907052e-15,  1.77635684e-15,
        1.77635684e-15])