# Итерационные методы решения СЛАУ

In [1]:
import sys

sys.path.append('..')

### 1. Метод Гаусса-Зейделя

In [2]:
import numpy as np
from modules.slae.solver.iterative.gauss_seidel import gauss_seidel

a = np.array([
    [8., -4., 1.],
    [-4., 8., -8.],
    [1., -4., 8.]
])

b = np.array([-13., 14., 16.])

x, iter = gauss_seidel(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 51


array([2.14285714, 9.10714286, 6.28571429])

##### Проверим найденное решение

Если $x$ решение $A * x = b$, то $r = A * x - b = 0$

In [3]:
r = np.dot(a, x) - b

r

array([-2.65488254e-09, -2.43792897e-09,  0.00000000e+00])

### 2. Метод Гаусса-Зейделя c релаксацией

In [10]:
from modules.slae.solver.iterative.gauss_seidel import gauss_seidel_relax

a = np.array([
    [8., -4., 1.],
    [-4., 8., -8.],
    [1., -4., 8.]
])

b = np.array([-13., 14., 16.])

x, iter = gauss_seidel_relax(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 29


array([2.14285714, 9.10714286, 6.28571429])

In [11]:
r = np.dot(a, x) - b

r

array([ 2.40511433e-09,  2.10141593e-09, -6.15969498e-11])

### 3. Метод сопряженных градиентов

In [13]:
from modules.slae.solver.iterative.conjugate_gradient import conjugate_gradient


a = np.array([
    [8., -4., 1.],
    [-4., 8., -8.],
    [1., -4., 8.]
])
b = np.array([-13., 14., 16.])

x, iter = conjugate_gradient(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 48


array([2.14285714, 9.10714286, 6.28571429])

In [14]:
r = np.dot(a, x) - b

r

array([-2.89084312e-11,  6.83755275e-11, -1.03099751e-10])

### 4. Метод сопряженных градиентов для разреженной матрицы

In [15]:
from modules.slae.solver.iterative.conjugate_gradient import conjugate_gradient_sym_triplet

t = [
    [0, 0, 8.],
    [0, 1, -4.],
    [0, 2, 1.],
    [1, 1, 8.],
    [1, 2, -8.],
    [2, 2, 8.],
]

b = np.array([-13., 14., 16.])

x, iter = conjugate_gradient_sym_triplet(t, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 3


array([-10.  , -21.25, -18.  ])

In [16]:
from modules.matrix.utils import matrix_sym_triplet_mult_vector

r = matrix_sym_triplet_mult_vector(t, x) - b

r

array([ 0.00000000e+00, -2.27373675e-13,  1.70530257e-13])