# Собственные значения и вектора матрицы

##### Нахождение собственного значения и вектора матрицы

In [7]:
import numpy as np

a = np.array([[8, -3, 1], [-3, 8, -3], [1, -3, 8]])

eigenvalues, eigenvectors = np.linalg.eig(a)

print("Собственные значения:")
print(eigenvalues)

print("\nСобственные векторы:")
print(eigenvectors)

Собственные значения:
[12.77200187  7.          4.22799813]

Собственные векторы:
[[-5.28450837e-01  7.07106781e-01  4.69829451e-01]
 [ 6.64439182e-01  6.75761546e-17  7.47342340e-01]
 [-5.28450837e-01 -7.07106781e-01  4.69829451e-01]]


##### Нормы собственных векторов

In [8]:
m = len(eigenvalues)

for i in range(m):
    print(f'Норма собственного вектора для λ = {eigenvalues[i]}, есть {np.dot(eigenvectors[:, i], eigenvectors[:, i])}')

Норма собственного вектора для λ = 12.772001872658771, есть 1.0000000000000002
Норма собственного вектора для λ = 7.0, есть 1.0
Норма собственного вектора для λ = 4.227998127341236, есть 0.9999999999999999


##### Проверим найденные собственные значения

$$A \cdot x = \lambda \cdot x$$

$$(A - \lambda I) \cdot x = 0$$

In [9]:
n = len(eigenvectors[0])

for i in range(m):
    b = np.diag([eigenvalues[i]] * n)
    c = a - b

    print('---')
    print(f'Проверка собственного значения λ = {eigenvalues[i]}')
    print(f'Детерминант матрицы A - λI = {np.linalg.det(c)}')
    print(f'(A - λI)x = {np.dot(c, eigenvectors[:, i])}')

---
Проверка собственного значения λ = 12.772001872658771
Детерминант матрицы A - λI = -2.922143476005612e-13
(A - λI)x = [ 5.10702591e-15 -4.55191440e-15  9.77071661e-17]
---
Проверка собственного значения λ = 7.0
Детерминант матрицы A - λI = 0.0
(A - λI)x = [-1.11022302e-16 -4.44089210e-16 -1.11022302e-16]
---
Проверка собственного значения λ = 4.227998127341236
Детерминант матрицы A - λI = -3.693048363995778e-14
(A - λI)x = [ 1.60982339e-15 -2.33146835e-15 -7.68347973e-16]
