# Прямые методы решения СЛАУ

In [21]:
import sys

sys.path.append('..')

### 1. Метод Гаусса

In [22]:
import numpy as np
from modules.slae.solver.direct.gauss_elimination import gauss_elimination

a = np.array([
    [8., -3., 1.],
    [-3., 8., -3.],
    [1., -3., 8.]
])

b = np.array([3., 3., 3.])

x = gauss_elimination(np.copy(a), np.copy(b))

x

array([0.61111111, 0.83333333, 0.61111111])

##### Проверим найденное решение

Если $x$ решение $A * x = b$, то $r = A * x - b = 0$

In [23]:
r = np.dot(a, x) - b

r

array([4.4408921e-16, 4.4408921e-16, 4.4408921e-16])

### 2. LU разложение

In [24]:
from modules.slae.solver.direct.lu_decomposition import lu_decomposition, lu_solve

a = np.array([
    [8., -3., 1.],
    [-3., 8., -3.],
    [1., -3., 8.]
])


lu = lu_decomposition(a.copy())

b = np.array([3., 3., 3.])

x = lu_solve(lu, b.copy())

x

array([0.61111111, 0.83333333, 0.61111111])

In [25]:
r = np.dot(a, x) - b

r

array([4.4408921e-16, 4.4408921e-16, 4.4408921e-16])

### 3. Разложение Холецкого

##### Пример №1

In [26]:
from modules.slae.solver.direct.choleski_decomposition import choleski_decomposition, choleski_solve

a = np.array([
    [8., -3., 1.],
    [-3., 8., -3.],
    [1., -3., 8.]
])

chol = choleski_decomposition(a.copy())

b = np.array([3., 3., 3.])

x = choleski_solve(chol, b.copy())

x

array([0.61111111, 0.83333333, 0.61111111])

In [27]:
r = np.dot(a, x) - b

r

array([-4.4408921e-16,  8.8817842e-16, -8.8817842e-16])

### 4. Трехдиагональная матрица

In [28]:
from modules.slae.solver.direct.lu_decomposition import lu_3_diag_decomposition, lu_3_diag_solve

d = np.ones((5)) * 5.
c = np.ones((4)) * (-1)

b = np.array([1., 1., 1., 1., 1.])

e = c.copy()

ct, dt, et = lu_3_diag_decomposition(c.copy(), d.copy(), e.copy())
x = lu_3_diag_solve(ct, dt, et, b.copy())

x

array([0.26363636, 0.31818182, 0.32727273, 0.31818182, 0.26363636])

##### Проверим найденное решение

Если $x$ решение $A * x = b$, то $r = A * x - b = 0$

In [29]:
from modules.matrix.utils import matrix_3_diag_mult_vector

r = matrix_3_diag_mult_vector(c, d, e, x) - b

r

array([ 0.00000000e+00,  0.00000000e+00, -2.22044605e-16,  0.00000000e+00,
        0.00000000e+00])