# Задание №2

In [1]:
import sys

sys.path.append('..')

### 1. Метод Гаусса

In [2]:
import numpy as np
from modules.slae.solver.direct.gauss_elimination import gauss_elimination

a = np.array([
    [7., -3., 1.],
    [-3., 7., -3.],
    [1., -3., 7.]
])

b = np.array([-2., 2., 2.])

x = gauss_elimination(np.copy(a), np.copy(b))

x

array([-0.1754386 ,  0.42105263,  0.49122807])

##### Проверим найденное решение

Если $x$ решение $A * x = b$, то $r = A * x - b = 0$

In [3]:
r = np.dot(a, x) - b

r

array([ 0.00000000e+00, -2.22044605e-16,  0.00000000e+00])

### 2. LU разложение

In [4]:
from modules.slae.solver.direct.lu_decomposition import lu_decomposition, lu_solve

a = np.array([
    [7., -3., 1.],
    [-3., 7., -3.],
    [1., -3., 7.]
])

lu = lu_decomposition(a.copy())

b = np.array([-2., 2., 2.])

x = lu_solve(lu, b.copy())

x

array([-0.1754386 ,  0.42105263,  0.49122807])

In [5]:
r = np.dot(a, x) - b

r

array([ 0.00000000e+00, -2.22044605e-16,  0.00000000e+00])

### 3. Разложение Холецкого

In [6]:
from modules.slae.solver.direct.choleski_decomposition import choleski_decomposition, choleski_solve

a = np.array([
    [7., -3., 1.],
    [-3., 7., -3.],
    [1., -3., 7.]
])

chol = choleski_decomposition(a.copy())

b = np.array([-2., 2., 2.])

x = choleski_solve(chol, b.copy())

x

array([-0.1754386 ,  0.42105263,  0.49122807])

In [7]:
r = np.dot(a, x) - b

r

array([ 2.22044605e-16,  4.44089210e-16, -4.44089210e-16])

### 4. Трехдиагональная матрица

In [8]:
from modules.slae.solver.direct.lu_decomposition import lu_3_diag_decomposition, lu_3_diag_solve

d = np.ones((5)) * 4.
c = np.ones((4)) * (-1)

b = np.array([1., -1., 1., -1., 1.])

e = c.copy()

ct, dt, et = lu_3_diag_decomposition(c.copy(), d.copy(), e.copy())
x = lu_3_diag_solve(ct, dt, et, b.copy())

x

array([ 0.21153846, -0.15384615,  0.17307692, -0.15384615,  0.21153846])

##### Проверим найденное решение

Если $x$ решение $A * x = b$, то $r = A * x - b = 0$

In [9]:
from modules.matrix.utils import matrix_3_diag_mult_vector

r = matrix_3_diag_mult_vector(c, d, e, x) - b

r

array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.11022302e-16,
       0.00000000e+00])