# Итерационные методы решения СЛАУ

In [35]:
import sys

sys.path.append('..')

### 1. Метод Гаусса-Зейделя

In [36]:
import numpy as np
from modules.slae.solver.iterative.gauss_seidel import gauss_seidel

a = np.array([
    [9., -4., 1.],
    [-4., 9., -4.],
    [1., -4., 9.]
])

b = np.array([-3., 4., 6.])

x, iter = gauss_seidel(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 20


array([-0.05387931,  0.89655172,  1.07112069])

##### Проверим найденное решение

Если $x$ решение $A * x = b$, то $r = A * x - b = 0$

In [37]:
r = np.dot(a, x) - b

r

array([-1.72316827e-09, -5.58640245e-10, -8.88178420e-16])

### 2. Метод Гаусса-Зейделя c релаксацией

In [38]:
from modules.slae.solver.iterative.gauss_seidel import gauss_seidel_relax

a = np.array([
    [9, -4., 1.],
    [-4., 9., -4.],
    [1., -4., 9.]
])

b = np.array([-3., 4., 6.])

x, iter = gauss_seidel_relax(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 17


array([-0.05387931,  0.89655172,  1.07112069])

In [39]:
r = np.dot(a, x) - b

r

array([ 9.43424006e-10,  9.52029566e-11, -6.45048459e-11])

### 3. Метод сопряженных градиентов

In [40]:
from modules.slae.solver.iterative.conjugate_gradient import conjugate_gradient

a = np.array([
    [9., -4., 1.],
    [-4., 9., -4.],
    [1., -4., 9.]
])

b = np.array([-3., 4., 6.])

x, iter = conjugate_gradient(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 3


array([-0.05387931,  0.89655172,  1.07112069])

In [41]:
r = np.dot(a, x) - b

r

array([ 0.0000000e+00, -8.8817842e-16,  0.0000000e+00])

### 4. Метод сопряженных градиентов для разреженной матрицы

In [42]:
from modules.slae.solver.iterative.conjugate_gradient import conjugate_gradient_sym_triplet

t = [
    [0, 0, 9.],
    [0, 1, -4.],
    [0, 2, 1.],
    [1, 1, 9.],
    [1, 2, -4.],
    [2, 2, 9.],
]

b = np.array([-3., 4., 6.])

x, iter = conjugate_gradient_sym_triplet(t, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 3


array([-0.05387931,  0.89655172,  1.07112069])

In [43]:
from modules.matrix.utils import matrix_sym_triplet_mult_vector

r = matrix_sym_triplet_mult_vector(t, x) - b

r

array([-8.8817842e-16,  8.8817842e-16,  0.0000000e+00])