# Итерационные методы решения СЛАУ

In [1]:
import sys

sys.path.append('..')

### 1. Метод Гаусса-Зейделя

In [2]:
import numpy as np
from modules.slae.solver.iterative.gauss_seidel import gauss_seidel

a = np.array([
    [8., -3., 1.],
    [-3., 8., -3.],
    [1., -3., 8.]
])

b = np.array([3., 3., 3.])

x, iter = gauss_seidel(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 15


array([0.61111111, 0.83333333, 0.61111111])

##### Проверим найденное решение

Если $x$ решение $A * x = b$, то $r = A * x - b = 0$

In [3]:
r = np.dot(a, x) - b

r

array([-3.11962456e-10, -4.26356728e-11,  4.44089210e-16])

### 2. Метод Гаусса-Зейделя c релаксацией

In [4]:
from modules.slae.solver.iterative.gauss_seidel import gauss_seidel_relax

a = np.array([
    [8., -3., 1.],
    [-3., 8., -3.],
    [1., -3., 8.]
])

b = np.array([3., 3., 3.])

x, iter = gauss_seidel_relax(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 14


array([0.61111111, 0.83333333, 0.61111111])

In [5]:
r = np.dot(a, x) - b

r

array([-2.13543849e-10,  1.33272060e-10, -1.01656461e-11])

### 3. Метод сопряженных градиентов

In [6]:
from modules.slae.solver.iterative.conjugate_gradient import conjugate_gradient

a = np.array([
    [8., -3., 1.],
    [-3., 8., -3.],
    [1., -3., 8.]
])

b = np.array([3., 3., 3.])

x, iter = conjugate_gradient(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 2


array([0.61111111, 0.83333333, 0.61111111])

In [7]:
r = np.dot(a, x) - b

r

array([-4.4408921e-16,  0.0000000e+00, -4.4408921e-16])

### 4. Метод сопряженных градиентов для разреженной матрицы

In [8]:
from modules.slae.solver.iterative.conjugate_gradient import conjugate_gradient_sym_triplet

t = [
    [0, 0, 8.],
    [0, 1, -3.],
    [0, 2, 1.],
    [1, 1, 8.],
    [1, 2, -3.],
    [2, 2, 8.],
]

b = np.array([3., 3., 3.])

x, iter = conjugate_gradient_sym_triplet(t, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 2


array([0.61111111, 0.83333333, 0.61111111])

In [9]:
from modules.matrix.utils import matrix_sym_triplet_mult_vector

r = matrix_sym_triplet_mult_vector(t, x) - b

r

array([-4.4408921e-16,  0.0000000e+00, -4.4408921e-16])