# Прямые методы решения СЛАУ

In [18]:
import sys

sys.path.append('..')

### 1. Метод Гаусса

##### Пример №1

In [19]:
import numpy as np
from modules.slae.solver.direct.gauss_elimination import gauss_elimination

a = np.array([
    [6., -4., 1.],
    [-4., 6., -4.],
    [1., -4., 6.]
])

b = np.array([-14., 36., 6.])

x = gauss_elimination(np.copy(a), np.copy(b))

x

array([10., 22., 14.])

##### Проверим найденное решение

Если $x$ решение $A * x = b$, то $r = A * x - b = 0$

In [20]:
r = np.dot(a, x) - b

r

array([-1.77635684e-15,  2.13162821e-14, -3.55271368e-15])

##### Пример №2

In [22]:
a = np.array([
    [6., -4., 1.],
    [-4., 6., -4.],
    [1., -4., 6.]
])

b = np.array([22., -18., 7.])

x = gauss_elimination(np.copy(a), np.copy(b))

x

array([ 3.00000000e+00, -1.00000000e+00, -1.77635684e-16])

In [23]:
r = np.dot(a, x) - b

r

array([0., 0., 0.])

##### Пример №3

In [6]:
from modules.matrix.vandermode import vandermode

v = np.array([1.0, 1.2, 1.4, 1.6, 1.8, 2.0])
b = np.array([0.0, 1.0, 0.0, 1.0, 0.0, 1.0])

a = vandermode(v)

a_orig = a.copy()
b_orig = b.copy()

x = gauss_elimination(a, b)

det = np.prod(np.diagonal(a))

print(f'Решение СЛАУ x = {x}')
print(f'Детерминант матрицы A = {det}')
print(f'Остаточный член r = A*x - b: {np.dot(a_orig, x) - b_orig}')

Решение СЛАУ x = [   416.66666667  -3125.00000004   9250.00000012 -13500.00000017
   9709.33333345  -2751.00000003]
Детерминант матрицы A = -1.1324620799859046e-06
Остаточный член r = A*x - b: [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
 -3.45607987e-11  1.81898940e-11]


### 2. LU разложение

##### Пример №1

In [7]:
from modules.slae.solver.direct.lu_decomposition import lu_decomposition, lu_solve

a = np.array([
    [6., -4., 1.],
    [-4., 6., -4.],
    [1., -4., 6.]
])

lu = lu_decomposition(a.copy())

b = np.array([-14., 36., 6.])

x = lu_solve(lu, b.copy())

x

array([10., 22., 14.])

In [8]:
r = np.dot(a, x) - b

r

array([-1.77635684e-15,  2.13162821e-14, -3.55271368e-15])

##### Пример №2

In [24]:
a = np.array([
    [6., -4., 1.],
    [-4., 6., -4.],
    [1., -4., 6.]
])

b = np.array([22., -18., 7.])

lu = lu_decomposition(a.copy())
x = lu_solve(lu, b.copy())

x

array([ 3., -1.,  0.])

In [25]:
r = np.dot(a, x) - b

r

array([0.0000000e+00, 0.0000000e+00, 8.8817842e-16])

##### Пример №3

In [11]:
v = np.array([1.0, 1.2, 1.4, 1.6, 1.8, 2.0])
b = np.array([0.0, 1.0, 0.0, 1.0, 0.0, 1.0])

a = vandermode(v)

lu = lu_decomposition(a.copy())
x = lu_solve(lu, b.copy())

print(f'Решение СЛАУ x = {x}')
print(f'Остаточный член r = A*x - b: {np.dot(a_orig, x) - b_orig}')

Решение СЛАУ x = [   416.66666667  -3125.00000004   9250.00000012 -13500.00000017
   9709.33333345  -2751.00000003]
Остаточный член r = A*x - b: [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
 -3.45607987e-11  1.81898940e-11]


### 3. Разложение Холецкого

##### Пример №1

In [12]:
from modules.slae.solver.direct.choleski_decomposition import choleski_decomposition, choleski_solve

a = np.array([
    [6., -4., 1.],
    [-4., 6., -4.],
    [1., -4., 6.]
])

chol = choleski_decomposition(a.copy())

b = np.array([-14., 36., 6.])

x = choleski_solve(chol, b.copy())

x

array([10., 22., 14.])

In [13]:
r = np.dot(a, x) - b

r

array([ 1.77635684e-15, -2.13162821e-14,  3.55271368e-15])

##### Пример №2

In [14]:
a = np.array([
    [6., -4., 1.],
    [-4., 6., -4.],
    [1., -4., 6.]
])

b = np.array([22., -18., 7.])

chol = choleski_decomposition(a.copy())
x = choleski_solve(chol, b.copy())

x

array([ 3.00000000e+00, -1.00000000e+00,  7.10542736e-16])

In [15]:
r = np.dot(a, x) - b

r

array([3.55271368e-15, 0.00000000e+00, 0.00000000e+00])

### 4. Трехдиагональная матрица

In [16]:
from modules.slae.solver.direct.lu_decomposition import lu_3_diag_decomposition, lu_3_diag_solve

d = np.ones((5)) * 2.
c = np.ones((4)) * (-1)

b = np.array([5., -5., 4., -5., 5.])

e = c.copy()

ct, dt, et = lu_3_diag_decomposition(c.copy(), d.copy(), e.copy())
x = lu_3_diag_solve(ct, dt, et, b.copy())

x

array([ 2., -1.,  1., -1.,  2.])

##### Проверим найденное решение

Если $x$ решение $A * x = b$, то $r = A * x - b = 0$

In [17]:
from modules.matrix.utils import matrix_3_diag_mult_vector

r = matrix_3_diag_mult_vector(c, d, e, x) - b

r

array([0., 0., 0., 0., 0.])