# Direct Methods for Solving System of Linear Algebraic Equations

In [37]:
import sys

sys.path.append('..')

### 1. Gauss Elimination Method

In [38]:
import numpy as np
from modules.slae.solver.direct.gauss_elimination import gauss_elimination

a = np.array([
    [6., -4., 1.],
    [-4., 6., -4.],
    [1., -4., 6.]
])

b = np.array([-14., 36., 6.])

x = gauss_elimination(a, b)

x

array([10., 22., 14.])

##### Let's check the solution found

If $x$ is a solution to $A * x = b$, then $r = A * x - b = 0$

In [39]:
r = np.dot(a, x) - b

r

array([1.77635684e-15, 2.13162821e-14, 0.00000000e+00])

### 2. LU factorization

In [40]:
from modules.slae.solver.direct.lu_decomposition import lu_decomposition, lu_solve

a = np.array([
    [6., -4., 1.],
    [-4., 6., -4.],
    [1., -4., 6.]
])

lu = lu_decomposition(a)

b = np.array([-14., 36., 6.])

x = lu_solve(lu, b)

x

array([10., 22., 14.])

In [41]:
r = np.dot(a, x) - b

r

array([1.77635684e-15, 2.13162821e-14, 0.00000000e+00])

### 3. Choleski’s Decomposition

In [42]:
from modules.slae.solver.direct.choleski_decomposition import choleski_decomposition, choleski_solve

a = np.array([
    [6., -4., 1.],
    [-4., 6., -4.],
    [1., -4., 6.]
])

chol = choleski_decomposition(a)

b = np.array([-14., 36., 6.])

x = choleski_solve(chol, b)

x

array([10., 22., 14.])

In [43]:
r = np.dot(a, x) - b

r

array([-1.77635684e-15, -2.13162821e-14,  0.00000000e+00])

### 4. Tridiagonal matrix

$
A = \begin{pmatrix}
    2 & -1 & 0 & 0 & 0 \\
    -1 & 2 & -1 & 0 & 0 \\
    0 & -1 & 2 & -1 & 0 \\ 
    0 & 0 & -1 & 2 & -1 \\ 
    0 & 0 & 0 & -1 & 2  
\end{pmatrix},\quad
b = \begin{pmatrix}
    5 \\
    -5 \\
    4 \\ 
    -5 \\ 
    5  
\end{pmatrix}
$

In [44]:
from modules.slae.solver.direct.lu_decomposition import lu_3_diag_decomposition, lu_3_diag_solve

d = np.ones((5)) * 2.
c = np.ones((4)) * (-1)

b = np.array([5., -5., 4., -5., 5.])

e = c.copy()

ct, dt, et = lu_3_diag_decomposition(c, d, e)
x = lu_3_diag_solve(ct, dt, et, b)

x

array([ 2., -1.,  1., -1.,  2.])

##### Let's verify the solution we found

If $x$ is the solution $A * x = b$, then $r = A * x - b = 0$

In [45]:
from modules.matrix.utils import matrix_3_diag_mult_vector

r = matrix_3_diag_mult_vector(c, d, e, x) - b

r

array([0., 0., 0., 0., 0.])