# Итерационные методы решения СЛАУ

In [1]:
import sys

sys.path.append('..')

### 1. Метод Гаусса-Зейделя

In [2]:
import numpy as np
from modules.slae.solver.iterative.gauss_seidel import gauss_seidel

a = np.array([
    [4., -1., 1.],
    [-1., 4., -2.],
    [1., -2., 4.]
])

b = np.array([12., -1., 5.])

x, iter = gauss_seidel(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 14


array([3., 1., 1.])

##### Проверим найденное решение

Если $x$ решение $A * x = b$, то $r = A * x - b = 0$

In [3]:
r = np.dot(a, x) - b

r

array([-1.01250563e-10,  2.07674766e-10,  0.00000000e+00])

### 2. Метод Гаусса-Зейделя c релаксацией

In [4]:
from modules.slae.solver.iterative.gauss_seidel import gauss_seidel_relax

a = np.array([
    [4., -1., 1.],
    [-1., 4., -2.],
    [1., -2., 4.]
])

b = np.array([12., -1., 5.])

x, iter = gauss_seidel_relax(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 14


array([3., 1., 1.])

In [5]:
r = np.dot(a, x) - b

r

array([-1.01250563e-10,  2.07674766e-10,  0.00000000e+00])

### 3. Метод сопряженных градиентов

In [6]:
from modules.slae.solver.iterative.conjugate_gradient import conjugate_gradient

a = np.array([
    [4., -1., 1.],
    [-1., 4., -2.],
    [1., -2., 4.]
])

b = np.array([12., -1., 5.])

x, iter = conjugate_gradient(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 3


array([3., 1., 1.])

In [7]:
r = np.dot(a, x) - b

r

array([ 1.77635684e-15, -8.88178420e-16,  1.77635684e-15])