# Iterative Methods for Solving System of Linear Algebraic Equations 

In [11]:
import sys

sys.path.append('..')

### 1. Gauss-Seidel Method

In [12]:
import numpy as np
from modules.slae.solver.iterative.gauss_seidel import gauss_seidel

a = np.array([
    [4., -1., 1.],
    [-1., 4., -2.],
    [1., -2., 4.]
])

b = np.array([12., -1., 5.])

x, iter = gauss_seidel(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 14


array([3., 1., 1.])

In [13]:
r = np.dot(a, x) - b

r

array([-1.01250563e-10,  2.07674766e-10,  0.00000000e+00])

### 2. Gauss-Seidel with Relaxation

In [14]:
from modules.slae.solver.iterative.gauss_seidel import gauss_seidel_relax

a = np.array([
    [4., -1., 1.],
    [-1., 4., -2.],
    [1., -2., 4.]
])

b = np.array([12., -1., 5.])

x, iter = gauss_seidel_relax(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 14


array([3., 1., 1.])

In [15]:
r = np.dot(a, x) - b

r

array([ 9.97992800e-11,  2.38632225e-10, -2.16822116e-11])