# Собственные значения и вектора матрицы

### Пример №1

##### Нахождение собственного значения и вектора матрицы

In [1]:
import numpy as np

a = np.array([[1, 2], [3, 4]])

eigenvalues, eigenvectors = np.linalg.eig(a)

print("Собственные значения:")
print(eigenvalues)

print("\nСобственные векторы:")
print(eigenvectors)

Собственные значения:
[-0.37228132  5.37228132]

Собственные векторы:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


##### Нормы собственных векторов

In [2]:
m = len(eigenvalues)

for i in range(m):
    print(f'Норма собственного вектора для λ = {eigenvalues[i]}, есть {np.dot(eigenvectors[:, i], eigenvectors[:, i])}')

Норма собственного вектора для λ = -0.3722813232690143, есть 1.0000000000000002
Норма собственного вектора для λ = 5.372281323269014, есть 1.0


##### Проверим найденные собственные значения

$$A \cdot x = \lambda \cdot x$$

$$(A - \lambda I) \cdot x = 0$$

In [3]:
n = len(eigenvectors[0])

for i in range(m):
    b = np.diag([eigenvalues[i]] * n)
    c = a - b

    print('---')
    print(f'Проверка собственного значения λ = {eigenvalues[i]}')
    print(f'Детерминант матрицы A - λI = {np.linalg.det(c)}')
    print(f'(A - λI)x = {np.dot(c, eigenvectors[:, i])}')

---
Проверка собственного значения λ = -0.3722813232690143
Детерминант матрицы A - λI = 0.0
(A - λI)x = [0. 0.]
---
Проверка собственного значения λ = 5.372281323269014
Детерминант матрицы A - λI = 0.0
(A - λI)x = [-2.22044605e-16  2.22044605e-16]


### Пример №2

##### Нахождение собственного значения и вектора матрицы

In [4]:
a = np.array([[1, -1, 0], [-1, 2, -1], [0, -1, 1]])

eigenvalues, eigenvectors = np.linalg.eig(a)

print("Собственные значения:")
print(eigenvalues)

print("\nСобственные векторы:")
print(eigenvectors)

Собственные значения:
[ 3.00000000e+00  1.00000000e+00 -3.36770206e-17]

Собственные векторы:
[[-4.08248290e-01 -7.07106781e-01  5.77350269e-01]
 [ 8.16496581e-01  2.61214948e-16  5.77350269e-01]
 [-4.08248290e-01  7.07106781e-01  5.77350269e-01]]


##### Нормы собственных векторов

In [5]:
m = len(eigenvalues)

for i in range(m):
    print(f'Норма собственного вектора для λ = {eigenvalues[i]}, есть {np.dot(eigenvectors[:, i], eigenvectors[:, i])}')

Норма собственного вектора для λ = 2.999999999999999, есть 1.0
Норма собственного вектора для λ = 0.9999999999999998, есть 0.9999999999999999
Норма собственного вектора для λ = -3.367702055640532e-17, есть 0.9999999999999999


##### Проверим найденные собственные значения

$$A \cdot x = \lambda \cdot x$$

$$(A - \lambda I) \cdot x = 0$$

In [6]:
m = len(eigenvalues)
n = len(eigenvectors[0])

for i in range(m):
    b = np.diag([eigenvalues[i]] * n)
    c = a - b

    print('---')
    print(f'Проверка собственного значения λ = {eigenvalues[i]}')
    print(f'Детерминант матрицы A - λI = {np.linalg.det(c)}')
    print(f'(A - λI)x = {np.dot(c, eigenvectors[:, i])}')

---
Проверка собственного значения λ = 2.999999999999999
Детерминант матрицы A - λI = 5.329070518200744e-15
(A - λI)x = [-1.11022302e-15  4.44089210e-16 -1.11022302e-16]
---
Проверка собственного значения λ = 0.9999999999999998
Детерминант матрицы A - λI = -4.4408920985006143e-16
(A - λI)x = [-4.18224194e-16  3.91703435e-17 -1.04205703e-16]
---
Проверка собственного значения λ = -3.367702055640532e-17
Детерминант матрицы A - λI = 0.0
(A - λI)x = [-1.11022302e-16  2.22044605e-16 -2.22044605e-16]
