# Conjugate Gradient Method

In [17]:
import sys

sys.path.append('..')

### 1. Conjugate Gradient Method

In [18]:
import numpy as np
from modules.slae.solver.iterative.conjugate_gradient import conjugate_gradient

a = np.array([
    [4., -1., 1.],
    [-1., 4., -2.],
    [1., -2., 4.]
])

b = np.array([12., -1., 5.])

x, iter = conjugate_gradient(a, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 3


array([3., 1., 1.])

In [19]:
r = np.dot(a, x) - b

r

array([ 1.77635684e-15, -8.88178420e-16,  1.77635684e-15])

### 2. Conjugate Gradient Method for Sparse Matrix

$
A = \begin{pmatrix}
    3 & 0 & -1 \\
    0 & 4 & -2 \\
    -1 & -2 & 5 \\ 
\end{pmatrix},\quad
b = \begin{pmatrix}
    4 \\
    10 \\
    -10
\end{pmatrix}
$

In [20]:
from modules.slae.solver.iterative.conjugate_gradient import conjugate_gradient_sym_triplet

t = [
    [0, 0, 3.],
    [0, 2, -1.],
    [1, 1, 4.],
    [1, 2, -2.],
    [2, 2, 5.]
]

b = np.array([4., 10., -10.])

x, iter = conjugate_gradient_sym_triplet(t, b, 10**-9, 1000)

print(f'iterations: {iter}')

x

iterations: 3


array([ 1.,  2., -1.])

In [21]:
from modules.matrix.utils import matrix_sym_triplet_mult_vector

r = matrix_sym_triplet_mult_vector(t, x) - b

r

array([-4.4408921e-16,  0.0000000e+00,  0.0000000e+00])